### PR TITLE
Enforce `#nullable enable` in source packages

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes build failures in https://github.com/dotnet/dotnet/pull/8731

```
src\sdk\artifacts\.packages\microsoft.codeanalysis.buildclient\5.12.0-ci\contentFiles\cs\net10.0\IBuildEnvironment.cs(16,18): error CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.
```

And ensures they don't happen in the future.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/85067)

### CODE REVIEW

File: eng/targets/Imports.targets [hunk 1]
```diff
@@ -106,6 +106,8 @@
       Updating a reference to this package to a newer version of the package may require changes in the referencing project.
       No compatibility guarantees are provided.
     </PackageDescription>
+    <!-- Files must individually enable nullable in source packages -->
```
Comment (333fred) [inline eng/targets/Imports.targets]: Consider including reasoning.

**Review by 333fred — APPROVED** [review]
