### PR TITLE
Allow adding `scoped` or removing `[UnscopedRef]` for override, interface implementation, or delegate conversion

### LINKED ISSUE #62340: Allow adding `scoped` or removing `[UnscopedRef]` for override, interface implementation, or delegate conversion
From [spec](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#rules-method-arguments-must-match):

> The signature for an override, interface implementation or `delegate` conversion can: 
> - Add `scoped` to a `ref` or `in` parameter
> - Add `scoped` to a `ref struct` parameter 
> - Remove `[UnscopedRef]` from an `out` parameter
> - Remove `[UnscopedRef]` from a `ref` parameter of a `ref struct` type
>
> Any other difference with respect to `scoped` will be considered an error.

### LINKED ISSUE #63761: Error overriding a method with an implicitly scoped parameter with -langversion:10
An error is reported overriding a method with an implicitly scoped parameter when the override is compiled with `-langversion:10`.

Compile base class with `-langversion:11`
```csharp
public abstract class A<T>
{
    public abstract void F(out T t);
}
```

Compile derived class with `-langversion:10` and .NET 6
```csharp
class B : A<int>
{
    // error CS8987: The 'scoped' modifier of parameter 'i' doesn't match overridden or implemented member.
    public override void F(out int i) { i = 0; }
}
```

Since `scoped` cannot be used with `-langversion:10`, perhaps the error should be a warning in this case.

### PR DESCRIPTION
**Pull request by cston**
See low-level-struct-improvements.md [update](https://github.com/dotnet/csharplang/pull/6448).

Fixes #62340.
Fixes #63761.

### CODE REVIEW

**Comment by cston** [comment]
This also fixes an issue introduced in https://github.com/dotnet/roslyn/pull/63461 that prevents moving to the latest compiler. 

Specifically, the following should compile without errors:

Compile with `-langversion:10`
```csharp
public delegate void D1<T>(out T t1);
```
Compile with `-langversion:11`
```csharp
class Program
{
    static void F1(out int i1) { i1 = 0; }
    static void Main()
    {
        // error CS8986: The 'scoped' modifier of parameter 'i1' doesn't match target 'D1<int>'
        D1<int> d1 = F1;
    }
}
```

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 1]
```diff
@@ -9208,49 +9201,43 @@ class Program
     static ref R M5(ref R x, scoped ref R y) => ref x;
     static void Implicit()
     {
-        D1 dA = M2;
-        D2 d2 = M1;
+        D1 d1 = M2;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9204]: Can we please make the numbers line up with `DX` and `MX`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 2]
```diff
@@ -9208,49 +9201,43 @@ class Program
...
+        D2 d2 = M1; // 1
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9205]: it would be helpful to add these trailing comments on all the tests where the diagnostics changed. Also, it looks like the comments are incomplete in this test. I would expect comments for declarations of 'M3' and 'M5'.

Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9205]: > I would expect comments for declarations of 'M3' and 'M5'.

I thought it would be clearer to have comments for the diagnostics related to `scoped` mismatch only.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9204]: I suppose someone will be confused, no matter what you name these.

**Review by 333fred — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]

**Comment by cston** [comment]
@333fred, @RikkiGibson, please review since this PR has been updated to: report diagnostics for unsafe differences only; and report warnings rather than errors for modules compiled with `-langversion:10` or earlier.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 3]
```diff
@@ -1368,6 +1370,63 @@ TypeWithAnnotations getNotNullIfNotNullOutputType(TypeWithAnnotations outputType
...
+            // ...
+            int nRefParametersRequired;
+            if (method.ReturnType.IsRefLikeType ||
+                (method.RefKind is RefKind.Ref or RefKind.RefReadOnly))
+            {
+                nRefParametersRequired = 1;
+            }
+            else if (parameters.Any(p => (p.RefKind is RefKind.Ref or RefKind.Out) && p.Type.IsRefLikeType))
+            {
+                nRefParametersRequired = 2; // including the parameter found above
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1398]: I wasn't sure if this will need to be modified to account for the upcoming `ReturnOnlyScope` change. Perhaps at that time it would be worth changing this to try an approach where we simulate the base calling into the derived and see if escape rules are satisfied.

```cs
class Base
{
    public virtual Span<byte> M(scoped ref byte input)
    {
        // if we could call Derived.M like this, would we satisfy escape rules?
        return Derived.M(ref input);
    }
}
class Derived : Base
{
    public override Span<byte> M(ref byte input)
    {
    }
}
```

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler it would be great to get this in soon, as the many diagnostic changes are prone to cause conflicts with other PRs.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 4]
```diff
@@ -9632,71 +9618,283 @@ public void DelegateConversions_07()
...
+                Diagnostic(ErrorCode.ERR_ScopedMismatchInParameterOfTarget, "([UnscopedRef] out R<int> r) => { r = default; return ref F(); }").WithArguments("r", "D5<int>").WithLocation(35, 30));
+        }
+
+        [Theory]
+        [InlineData("ref")]
+        [InlineData("in ")]
+        public void DelegateConversions_08(string refModifier)
+        {
+            var source =
+$@"ref struct R<T> {{ }}
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9695]: Nit: remember that we have raw strings, and you can do `$$"""` :).

**Review by 333fred — APPROVED** [review]
