### ISSUE TITLE
C# 9 Covariant Returns feature does not work properly with Generic Interfaces

### ISSUE THREAD

**Issue by fitdev** [dotnet/roslyn#49108]
**Version Used**: 

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Using latest VS Community 2019 16.8 Preview 6

**Steps to Reproduce**:

```cs
    public class MyContainerClass<T> : IMyContainer<T> { // <-- CS0738: 'MyContainerClass<T>' does not implement interface member 'IMyContainer<T>.Children'. 'MyContainerClass<T>.Children' cannot implement 'IMyContainer<T>.Children' because it does not have the matching return type of 'IEnumerable<T>'.
      public IReadOnlyCollection<T> Children { get; }
    }

    public interface IMyContainer<out T> {
      IEnumerable<T> Children { get; }
    }
```

**Expected Behavior**:
It should be possible for `MyContainerClass<T>.Children` to implement `IMyContainer<T>.Children` since `T` is covariant and `IReadOnlyCollection<T>` inherits from `IEnumerable<T>`.

**Actual Behavior**:

```
CS0738: 'MyContainerClass<T>' does not implement interface member 'IMyContainer<T>.Children'. 'MyContainerClass<T>.Children' cannot implement 'IMyContainer<T>.Children' because it does not have the matching return type of 'IEnumerable<T>'.
```

**Comment by svick** [comment]
As I understand it, C# 9.0 covariant returns only work for overrides, they don't work for interface implementations. [The draft spec of the feature](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/covariant-returns.md) does mention interface implementation, but only after this note:

> The remainder of the draft specification below proposes a further extension to covariant returns of interface methods to be considered later.

So, your code might work in some future version of C#, but it's expected that it doesn't work in C# 9.0.

**Comment by jaredpar** [comment]
@svick is correct here, this feature is only for `overrides`, not for `interface` implementations.
