### ISSUE TITLE
Nuget package incompatibility between latest versions of CodeDom.Providers.DotNetCompilerPlatform and .Net.Compilers

### ISSUE THREAD

**Issue by mrchops1024** [dotnet/roslyn#18533]
**Version Used**: 
Latest version of VS2017

**Steps to Reproduce**:

1.  Create a ASP.NET web application with WebAPI
2.  Upgrade nuget package for Microsoft.Net.Compilers from v1.3.2 (default) to v2.0.1
3.  Publish (I tested via folder publishing)
4.  Test API

**Expected Behavior**:
I would expect the API to work without errors.

**Actual Behavior**:
>Compilation Error
>
>Description: An error occurred during the compilation of a resource required to service this request. >Please review the following specific error details and modify your source code appropriately. 
>
>Compiler Error Message: The compiler failed with error code -532462766.
>
>
>Show Detailed Compiler Output:
>
>
>Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.36366`

If I downgrade the Microsoft.Net.Compilers package back down to 1.3.2 everything works fine. Dependency for Microsoft.CodeDom.Providers.DotNetCompilerPlatform says it works with >=1.3.2 of .Net.Compilers, but perhaps it's not compatible with v2.0.1.

**Comment by pumamood** [comment]
same issue for me

**Comment by Tankzor** [comment]
ditto

**Comment by LenonLopez** [comment]
I've encountered this issue as well.

**Comment by CircusAlchemist** [comment]
Same here.  Published vs Local seems like a dependency issue, doesn't it?

**Comment by jaredpar** [comment]
CC @Jinhuafei who owns the DotNetCompilerPlatform package.

What version of .NET is running on your web server here: 4.5.2 or 4.6+?  The 2.0 version of the compiler requires 4.6 and higher in order to run.  This requirement was accidentally left off of our RTM config and hence produces exceptions vs. an explicit message.  This was recently fixed though and will be a part of the next release.

**Comment by CircusAlchemist** [comment]
Yes, the version on the server is 4.5.2.  Thanks Jared.

**Comment by jaredpar** [comment]
FYI: here is the PR which added the appropriate app.config entry. 

https://github.com/dotnet/roslyn/pull/18018

**Comment by dauger** [comment]
I'm seeing this issue on a 2012 R2 server with 4.6.1 installed. I've tried targeting both 4.6 and 4.6.1 to no avail.

> Compilation Error
>
>Description: An error occurred during the compilation of a resource required to service this request. >Please review the following specific error details and modify your source code appropriately. 
>
>Compiler Error Message: The compiler failed with error code -532462766.
>
>Show Detailed Compiler Output:
> ...
>
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1087.0

FWIW I also tried Microsoft.Net.Compilers v2.1.0

**Comment by jaredpar** [comment]
@dauger 

It's likely you're seeing a different issue here than the 4.5.X dependency problem. That error code is the general unhandled exception message. 

Do you have a repo / code snippet you can share where this crash is happening? That will help us dig into this problem.

Note: closing this particular issue because we're pretty confident the root 4.5 issue is addressed. Will open a new issue to track this problem when we get a sniipet.

**Comment by PrismaPhonic** [comment]
I'm experiencing this exact same issue.  Is there a fix?  If so it should be linked here even if this issue is closed.  I can't find any other issue that would help me resolve the problem

**Comment by jibboo** [comment]
Ran into this issue trying to install a NuGet package and code the same error:

`Microsoft.Net.Compilers 1.3.2' is not compatible with 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.5`

To resolve this, I installed the newer compiler option from : https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform

in Visual Studio --> Tools --> Nuget Package Manager --> Package Manager Console

run the code for the desired compiler version from that webpage:

`PM>  Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 2.0.1`
