### ISSUE TITLE
5.0.200 breaks implicit conversion of number literal to short

### ISSUE THREAD

**Issue by BickelLukas** [dotnet/roslyn#51624]
**Version Used**:  dotnet sdk 5.0.200

**Steps to Reproduce**:
consider the following code:
```
            var condition = true;
            short? x = condition ? 1 : 0;
```

this compiles fine in 5.0.103 but in 5.0.200 it throws a compilation error.

**Expected Behavior**:
The code should compile

**Actual Behavior**:
`error CS0266: Cannot implicitly convert type 'int' to 'short?'. An explicit conversion exists (are you missing a cast?)`

**Comment by rhaokiel** [comment]
Extended issue of #51597 (w/ byte)

**Comment by Youssef1313** [comment]
See https://github.com/dotnet/roslyn/issues/51450#issuecomment-785315705

**Comment by jaredpar** [comment]
This was an intentional change. That type of conversion was accidentally allowed in 16.8 and was fixed in 16.9. Primary issue is #49598
