### ISSUE TITLE
Breaking change: constant patterns and binary expressions

### ISSUE THREAD

**Issue by controlflow** [dotnet/roslyn#14641]
```c#
class C {
  // error CS1525: Invalid expression term 'string'
  object O => O is string + "";
}
```
This code no longer compiles in C# 7.0, since `string + ""` now parses as a constant pattern instead of type syntax and additive expression concatenating `""` literal with the results of `is` expression.

**Comment by controlflow** [comment]
I guess you have to raise the allowed binary operator precedence when parsing constant pattern from `> Precedence.Relational` to something higher...

**Comment by gafter** [comment]
It was a bug that the compiler accepted this before. The precedence of `+` is higher than the precedence for `is`, and therefore `is` cannot be an operand of `+`. This bug was fixed in the compiler in order to add support for pattern-matching. See https://github.com/dotnet/roslyn/issues/10492

**Comment by controlflow** [comment]
Thanks for clarifying, @gafter!
