### PR TITLE
Fixes #13228 and Fixes #17761

### LINKED ISSUE #13228: Need to see if we can unify implementations of CheckFeatureAvailability methods across Parser and Scanner
In VB, both Parser and Scanner expose API called CheckFeatureAvailability, but each has its own implementation. Moreover, it looks like implementation in the Parser doesn't quite handle experimental features.

### LINKED ISSUE #17761: [Bug] Forgot to update Localisation of Feature String.
[Comment in code](https://github.com/dotnet/roslyn/blob/1e38875dd13c712bf347050d7b27512bc8365a13/src/Compilers/VisualBasic/Portable/Parser/Parser.vb#L6171)
```
' Bug: It is too late in the release cycle to update localized strings.  As a short term measure we will output 
' an unlocalized string and fix this to be localized in the next release.
```

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Unifies `CheckFeatureAvailability` from `Scanner` and `Parser` into a utility class.
Minimises the number of functions.
Incorporating recent changes by @jcouv  
Add in the missed localization of the feature `Interpolation Strings`. 
~Fixes a minor where we don't correctly free a pooled string builder.~

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AlekseyTs** [comment]
@AdamSpeight2008 It looks like some tests are failing.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For review.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
@AlekseyTs 
The 4 signing failures seem to always fail on me locally. I'm not too bother about them so long as they work with Jenkins.
Think the issues are unrelated to this PR, maybe recent changes to `IOperation`

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+            Return Parser.ReportSyntaxError(node, ERRID.ERR_LanguageVersion, languageVersion.GetErrorName(), featureName, requiredVersion)
+        End Function
+
+        '''' <summary>
+        '''' Check to see if the given <paramref name="feature"/> is available with the <see cref="LanguageVersion"/>
+        '''' of the parser.
+        '''' </summary>
+        Protected Friend Shared Function CheckFeatureAvailability(parseOptions As VisualBasicParseOptions, feature As Feature) As Boolean
+            Dim featureFlag = feature.GetFeatureFlag()
+            If featureFlag IsNot Nothing Then Return parseOptions.Features.ContainsKey(featureFlag)
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Please use multi-line `If` here and in other cases below.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 2]
```diff
@@ -0,0 +1,53 @@
+﻿' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+Option Compare Binary
+Option Strict On
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: `Option` statements are not necessary. Options are set by the build, and these are the defaults.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+Imports Microsoft.CodeAnalysis.VisualBasic
+
+Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax
+
+    Friend Class FeatureUtils
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: `Module`

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+        Private Shared Function CheckLanguageVersion(languageVersion As LanguageVersion, feature As Feature) As Boolean
+            Dim required = feature.GetLanguageVersion()
+            Return required <= languageVersion
+        End Function
+
+        Protected Friend Shared Function ReportFeatureUnavailable(Of TNode As VisualBasicSyntaxNode)(feature As Feature, node As TNode, languageVersion As LanguageVersion) As TNode
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Why `Protected`? Are there derived types?

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 2 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: These are automatically brought in via the new file dialog.

**Comment by AdamSpeight2008** [comment]
If we go `module` route we could if we reorder the parameters so that the `feature` argument is first, make them extension methods.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 3 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: I made them `class` and `friend` so that I didn't have to go through a public api review.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 4 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Keep the scope as narrow as possible, and not public so a public api review isn't needed.

**Comment by AdamSpeight2008** [comment]
This fail locally. 
```
      InternalsVisibleToAndStrongNameTests.PublicKeyFromOptions_PublicSign [FAIL]
      InternalsVisibleToAndStrongNameTests.KeyFileFromAttributes_PublicSign [FAIL]
      InternalsVisibleToAndStrongNameTests.KeyContainerFromAttributes_PublicSign [FAIL]
      InternalsVisibleToAndStrongNameTests.PublicSign_IgnoreSourceAttributes [FAIL]
```

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 5]
```diff
@@ -28,7 +28,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax
         Private _possibleFirstStatementOnLine As PossibleFirstStatementKind = PossibleFirstStatementKind.Yes
         Private _recursionDepth As Integer
         Private _evaluatingConditionCompilationExpression As Boolean
-        Private ReadOnly _scanner As Scanner
+        Friend ReadOnly _scanner As Scanner
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: `_scanner` should not be exposed. `_scanner.Options` can be exposed as an `Options` property instead.

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb [hunk 6]
```diff
@@ -80,7 +80,9 @@ Friend Module ParserTestUtilities
             Dim errors = PooledStringBuilderPool.Allocate()
             AppendSyntaxErrors(tree.GetDiagnostics(), errors.Builder)
             Assert.Equal(root.ContainsDiagnostics, errors.Builder.Length > 0)
-            Assert.False(root.ContainsDiagnostics, errors.ToStringAndFree())
+            Dim result = errors.ToStringAndFree
+            Assert.False(root.ContainsDiagnostics, result)
```
Comment (AdamSpeight2008) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: This fixes a leaky pool object.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb (hunk 5 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: Note the change in visibility to make is accessible to the `FeatureUtils` module

File: src/Compilers/VisualBasic/Portable/VBResources.resx [hunk 7]
```diff
@@ -5476,4 +5476,10 @@
   <data name="ERR_BadSourceCodeKind" xml:space="preserve">
     <value>Provided source code kind is unsupported or invalid: '{0}'</value>
   </data>
+  <data name="ERRWRN_Last_Title" xml:space="preserve">
+    <value>Unable to load analyser assembly</value>
```
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/VBResources.resx]: This one needs to be checked as I had add it, so I could compile and test. So could be an issue when merging.

File: src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb [hunk 8]
```diff
@@ -115,7 +117,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax
                                                        declarations,
                                                        optionalTerminator)
 
-            Dim regionsAreAllowedEverywhere = Not haveRegionDirectives OrElse Parser.CheckFeatureAvailability(Feature.RegionsEverywhere)
+            Dim regionsAreAllowedEverywhere = Not haveRegionDirectives OrElse Feature.RegionsEverywhere.IsAvailable(_parser._scanner.Options)
```
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb]: @cston  This class is reason for the `Friend ReadOnly` change.

Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb]: `Parser` could expose an `Options` property rather than exposing `_scanner` which is arguably an implementation detail.

Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb]: @cston  Added a readonly property to Parser instead to access them.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 9]
```diff
@@ -73,6 +73,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax
             End Get
         End Property
 
+        Friend ReadOnly Property GetScannerOptions As VisualBasicParseOptions
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: The property could be named `Options` instead.

Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: @cston I'll do another review of the usages, as I think all of the feature utils usages can go through this method. If so, I'll rename it `Options` afterwards.

**Comment by AdamSpeight2008** [comment]
Just the regular (for me) 4 x test failures. See  #17929

File: .gitignore [hunk 10]
```diff
@@ -38,7 +38,7 @@ UnitTestResults.html
 *.nuget.props
 *.nuget.targets
 project.lock.json
-*.project.lock.json
+*project.lock.json
```
Comment (cston) [inline .gitignore]: Was this intentional? If not, please revert.

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb (hunk 6 above)
Comment (cston) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: Is there a difference between the two?

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb [hunk 11]
```diff
@@ -1973,7 +1972,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         IDS_LogoLine1 = 56007
         IDS_LogoLine2 = 56008
         IDS_VBCHelp = 56009
-        ' available: 56010
+        IDS_InvalidPreprocessorConstantType = 56010
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Is this used?

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb [hunk 12]
```diff
@@ -2004,5 +2003,6 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         FEATURE_BinaryLiterals
         FEATURE_Tuples
         FEATURE_IOperation
+        FEATURE_InterpolatedStrings
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Is this used?

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 13]
```diff
@@ -6155,61 +6161,6 @@ checkNullable:
             Return node.AddTrailingSyntax(b.ToList(), ERRID.ERR_Syntax)
         End Function
 
-        ''' <summary>
-        ''' Check to see if the given <paramref name="feature"/> is available with the <see cref="LanguageVersion"/>
-        ''' of the parser.  If it is not available a diagnostic will be added to the returned value.
-        ''' </summary>
-        Private Function CheckFeatureAvailability(Of TNode As VisualBasicSyntaxNode)(feature As Feature, node As TNode) As TNode
-            Return CheckFeatureAvailability(feature, node, _scanner.Options.LanguageVersion)
-        End Function
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: If this method was retained, and implemented as `feature.IsAvailable(Options, node)`, then much of the `Parser` code could be left unchanged.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 14]
```diff
@@ -0,0 +1,79 @@
+﻿' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax
+    ''' <summary>
+    ''' Utilies method to help with checking the availability of language features.
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: `Utility methods`

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb (hunk 6 above)
Comment (AdamSpeight2008) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: If the assert isn't thrown the string is never built and thus never freed.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 11 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Probably made a mistake when resolving a merge conflict. ( #17113 )

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb (hunk 13 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: Prefer the newer implementation so `_scanner` doesn't need a change of visibility.  The changes in the `parser` are rather minor.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 14 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Correcting.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 12 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: It's part of the fix for #17761

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb (hunk 6 above)
Comment (cston) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: `errors.ToStringAndFree()` will be invoked if execution reaches line 83, with or without this change.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 12 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Do we have a test for that message?

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 15]
```diff
@@ -0,0 +1,79 @@
...
+
+        ''' <summary>Returns false and reports an error if the feature is un-available.</summary>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="parseoptions">The parse options being used.</param>
+        ''' <param name="diagnostics">The diagnostics to which add this diagnostic.</param>
+        ''' <param name="location">The location to report the diagnotic.</param>
+        ''' <returns></returns>
+        <Runtime.CompilerServices.Extension>
+        Public Function IsAvailable(feature As Feature, parseoptions As VisualBasicParseOptions, diagnostics As DiagnosticBag, location As Location) As Boolean
+            If feature.IsAvailable(parseoptions) Then Return True
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Please use multi-line `If`.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 16]
```diff
@@ -0,0 +1,79 @@
...
+        ''' <summary>
+        '''  Check to see if the given <paramref name="feature"/> is available with the <see cref="LanguageVersion"/>
+        ''' of the parser.  If it is not available a diagnostic will be added to the returned value.
+        ''' </summary>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="parseoptions">The parse options being used.</param>
+        ''' <param name="node">The node to attach the potential diagnostic (Feature Unavailable).</param>
+        ''' <returns></returns>
+        <Runtime.CompilerServices.Extension>
+        Public Function IsAvailable(Of TNode As VisualBasicSyntaxNode)(feature As Feature, parseoptions As VisualBasicParseOptions, node As TNode) As TNode
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: The `VisualBasicParseOptions` argument is named differently in these methods: `options`, `parseOptions`, `parseoptions`. Perhaps just `options` everywhere.

File: src/Compilers/VisualBasic/Portable/VBResources.resx (hunk 7 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/VBResources.resx]: I think this can be removed.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 12 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: It should be covered by the exist tests. [Test](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Test/Syntax/Parser/ParseLanguageVersionTests.vb#L304)

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 16 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Done

File: src/Compilers/VisualBasic/Portable/VBResources.resx (hunk 7 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/VBResources.resx]: Removed

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 17]
```diff
@@ -0,0 +1,79 @@
...
+        ''' <summary>
+        '''  Check to see if the given <paramref name="feature"/> is available with the <see cref="LanguageVersion"/>
+        ''' of the parser.  If it is not available a diagnostic will be added to the returned value.
+        ''' </summary>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="options">The parse options being used.</param>
+        ''' <param name="node">The node to attach the potential diagnostic (Feature Unavailable).</param>
+        ''' <returns></returns>
+        <Runtime.CompilerServices.Extension>
+        Public Function IsAvailable(Of TNode As VisualBasicSyntaxNode)(feature As Feature, options As VisualBasicParseOptions, node As TNode) As TNode
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: If the function returns a `TNode` rather than a `Boolean`, it should not be called `IsAvailable`. Consider reverting to `CheckFeatureAvailability`.

**Comment by cston** [comment]
Please squash commits and do not include the merge of master in the set of commits since this change targets the master branch.

**Comment by AdamSpeight2008** [comment]
@cston Squished the commits down to one.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb [hunk 18]
```diff
@@ -754,6 +754,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         'ERR_UnableToOpenFile1 = 31027
         ERR_EventHandlerSignatureIncompatible2 = 31029
         ERR_ConditionalCompilationConstantNotValid = 31030
+        ERR_ProjectCCError1 = 31030
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Is this change intentional?

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb [hunk 19]
```diff
@@ -80,7 +80,7 @@ Friend Module ParserTestUtilities
             Dim errors = PooledStringBuilderPool.Allocate()
             AppendSyntaxErrors(tree.GetDiagnostics(), errors.Builder)
             Assert.Equal(root.ContainsDiagnostics, errors.Builder.Length > 0)
-            Assert.False(root.ContainsDiagnostics, errors.ToStringAndFree())
+			Assert.False(root.ContainsDiagnostics, errors.ToStringAndFree())
```
Comment (cston) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: Change can be reverted.

File: src/Compilers/VisualBasic/Portable/Lowering/ExpressionLambdaRewriter/ExpressionLambdaRewriter.vb [hunk 20]
```diff
@@ -47,45 +47,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Public ReadOnly Property ElementInitType As NamedTypeSymbol
             Get
-                If _elementInitType Is Nothing Then
-                    _elementInitType = Me._factory.WellKnownType(WellKnownType.System_Linq_Expressions_ElementInit)
-                End If
+                _elementInitType = If(_elementInitType, _factory.WellKnownType(WellKnownType.System_Linq_Expressions_ElementInit))
                 Return _elementInitType
             End Get
         End Property
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/ExpressionLambdaRewriter/ExpressionLambdaRewriter.vb]: The changes to `VisualBasic/Portable/Lowering/*` appear unrelated. Please revert.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 21]
```diff
@@ -0,0 +1,84 @@
...
+        ''' <summary>
+        '''  Check to see if the given <paramref name="feature"/> is available with the <see cref="LanguageVersion"/>
+        ''' of the parser.  If it is not available a diagnostic will be added to the returned value.
+        ''' </summary>
+        ''' <param name="node">The node to attach the potential diagnostic (Feature Unavailable).</param>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="options">The parse options being used.</param>
+        ''' <returns></returns>
+        <Runtime.CompilerServices.Extension>
+        Public Function CheckFeatureAvailable(Of TNode As VisualBasicSyntaxNode)(node As TNode, feature As Feature, options As VisualBasicParseOptions) As TNode
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Please use the original name `CheckFeatureAvailability`, for consistency with previous code and with the C# implementation.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 22]
```diff
@@ -0,0 +1,84 @@
...
+
+        ''' <summary>Returns false and reports an error if the feature is un-available.</summary>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="options">The parse options being used.</param>
+        ''' <param name="diagnostics">The diagnostics to which add this diagnostic.</param>
+        ''' <param name="location">The location to report the diagnotic.</param>
+        ''' <returns></returns>
+        <Runtime.CompilerServices.Extension>
+        Public Function IsAvailable(feature As Feature, options As VisualBasicParseOptions, diagnostics As DiagnosticBag, location As Location) As Boolean
+            If feature.IsAvailable(options) Then Return True
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Please use multi-line `If`.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 18 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Nope, its squish juice.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 23]
```diff
@@ -0,0 +1,84 @@
...
+        ''' <returns>True if the feature's language version is compatible with the specified language version.</returns>
+        <Runtime.CompilerServices.Extension>
+        Private Function IsInLanguageVersion(feature As Feature, options As VisualBasicParseOptions) As Boolean
+            Dim required = feature.GetLanguageVersion()
+            Dim current = options.LanguageVersion
+            Return required <= current
+        End Function
+
+        <Runtime.CompilerServices.Extension>
+        Private Function CheckFeatures(feature As Feature, options As VisualBasicParseOptions) As Boolean
```
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: @cston Keeping this as it checking the `VisualBasicParserOptions.Features`, easier to see that there two distinct checks;- Features and Language Version.

File: src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb [hunk 24]
```diff
@@ -4,6 +4,8 @@ Imports Microsoft.CodeAnalysis.Syntax.InternalSyntax
 Imports Microsoft.CodeAnalysis.Text
 Imports Microsoft.CodeAnalysis.VisualBasic.Symbols
 Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
+Imports Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.FeatureUtils
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb]: Is this `Imports` necessary, here or in other files where the use is within `Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax`?

**Comment by cston** [comment]
LGTM other than extra `Imports` statements.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb (hunk 24 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/BlockContexts/CompilationUnitContext.vb]: Only these need an import.
```
Binder_Attributes.vb
SyntaxFactory.vb
ImplementsHelper.vb
```

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
@dotnet/roslyn-compiler  Is there any feedback?

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
@cston  Any update on this PR?

**Comment by cston** [comment]
@dotnet/roslyn-compiler please provide a second review, thanks.

**Comment by agocke** [comment]
LGTM

**Comment by cston** [comment]
**Scenario**
Unify separate `CheckFeatureAvailability` implementations in the VB `Scanner` and `Parser` and include localizable string for reporting "interpolated string" feature not available.

**Bugs fixed**
#13228, #17761 

**Risk**
Low

**Performance impact**
None

**Is this a regression from a previous update?**
No

**How was the bug found?**
Code inspection

@jaredpar, @MeiChin-Tsai for approval

**Comment by jaredpar** [comment]
Looks like this has gotten a bit out of date.  Sorry been over busy lately.  Please rebase / merge this so there are no conflicts.

File: src/Compilers/Core/Portable/Operations/IOperationKind.cs [hunk 25]
```diff
@@ -168,7 +168,7 @@ public enum OperationKind
         /// <summary>Indicates an <see cref="IArrayInitializer"/>.</summary>
         ArrayInitializer = 0x405,
 
-        /// <summary>Indicates an <see cref="IVariableDeclaration"/>.</summary>
+        /// <summary>Indicates an <see cref="IVariableDeclarationGroup"/>.</summary>
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Operations/IOperationKind.cs]: Why was this renamed?  Seems unrelated to this change.

Comment (AdamSpeight2008) [inline src/Compilers/Core/Portable/Operations/IOperationKind.cs]: Bad Merge?

Comment (AdamSpeight2008) [inline src/Compilers/Core/Portable/Operations/IOperationKind.cs]: Commit 44a321c2

Comment (AdamSpeight2008) [inline src/Compilers/Core/Portable/Operations/IOperationKind.cs]: @jaredpar What is the fix? As this the

**Comment by MeiChin-Tsai** [comment]
approved. thx.

**Comment by AdamSpeight2008** [comment]
@jaredpar  Failure is around the recent change to `IVariableDeclaration`.
```
error CS0115: 'OperationTreeVerifier.VisitVariableDeclaration(IVariableDeclaration)': no suitable method found to override [D:\j\workspace\perf_correctn---991e8cc1\src\Test\Utilities\Portable\TestUtilities.csproj]
```
Don't know how correct.

**Comment by cston** [comment]
@AdamSpeight2008 The failure appears to be due to the changes to `src/Compilers/Core/Portable`, perhaps from merge conflicts. Please revert those files since those are not related to this PR.

File: src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb (hunk 19 above)
Comment (cston) [inline src/Compilers/Test/Utilities/VisualBasic/ParserTestUtilities.vb]: Please revert.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 18 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Please revert the addition of `ERR_ProjectCCError1`.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 26]
```diff
@@ -0,0 +1,84 @@
...
+            Return ((featureFlag IsNot Nothing) AndAlso options.Features.ContainsKey(featureFlag))
+        End Function
+
+        ''' <summary>Report the unavailibility of a language feature.</summary>
+        ''' <typeparam name="TNode"></typeparam>
+        ''' <param name="feature">Language feature to report as unavailable.</param>
+        ''' <param name="options">The parse options being used.</param>
+        ''' <param name="node">The node to attach the diagnostic (Feature Unavailable).</param>
+        ''' <returns>Return the node with the diagnostic attached to it.</returns>
+        <Runtime.CompilerServices.Extension>
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: Please add `Imports System.Runtime.CompilerServices`.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb [hunk 27]
```diff
@@ -0,0 +1,83 @@
...
+        ''' </summary>
+        ''' <param name="node">The node to attach the potential diagnostic (Feature Unavailable).</param>
+        ''' <param name="feature">Language feature to check is available.</param>
+        ''' <param name="options">The parse options being used.</param>
+        <Extension>
+        Public Function CheckFeatureAvailable(Of TNode As VisualBasicSyntaxNode)(node As TNode, feature As Feature, options As VisualBasicParseOptions) As TNode
+            Return If(feature.IsAvailable(options), node, feature.ReportFeatureUnavailable(options, node))
+        End Function
+
+        ''' <summary>Returns false and reports an error if the feature is un-available.</summary>
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: `unavailable`

Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: @cston Would you mind review the texts in the tags, as I'm dyslexic and may have made others and grammar errors ?

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

File: src/Compilers/VisualBasic/Portable/Parser/ParseConditional.vb [hunk 28]
```diff
@@ -8,10 +8,12 @@
 Imports System.Globalization
 Imports Microsoft.CodeAnalysis.Syntax.InternalSyntax
 Imports InternalSyntaxFactory = Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.SyntaxFactory
+Imports Microsoft.CodeAnalysis.VisualBasic.Syntax.InternalSyntax.FeatureUtils
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Parser/ParseConditional.vb]: `Imports` is not required here or in other files containing `InternalSyntax` types below.

File: src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb (hunk 27 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Utilities/FeatureUtils.vb]: @AdamSpeight2008 the comments look good, thanks.

File: src/Compilers/VisualBasic/Portable/Parser/ParseConditional.vb (hunk 28 above)
Comment (AdamSpeight2008) [inline src/Compilers/VisualBasic/Portable/Parser/ParseConditional.vb]: @cston  This import is to bring the extension methods into scope.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
@jaredpar @cston May I have a review please.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by jaredpar** [comment]
The windows_build_correctness_prtest is a legitimate failure.  The compiler generated files are out of date.

**Comment by AdamSpeight2008** [comment]
@jaredpar If there compiler generated how can they be out of date? 😕

**Comment by jaredpar** [comment]
They are generated on demand and checked into the source tree.

**Comment by AdamSpeight2008** [comment]
@dotnet/roslyn-compiler please review.

**Comment by AdamSpeight2008** [comment]
Unable to figure a fix for the `generated files` no being up to date, so redid fix on a more recent master. 
#19319
