### ISSUE TITLE
[.NET 6] [Source Compat Failure] DiscordChatExporter app doesn't build with default target 3.1 with .net6 SDK 

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/roslyn#51050]
**Application Name:**  DiscordChatExporter
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.1.21080.2

 **Verify Scenarios:**
1) App Target 3.1 + .NET Core SDK build 6.0.100-preview.1.21080.2: Fail
2) App Target 3.1 + .NET Core SDK build 5.0.102: Pass
3) App Re-Target 5.0 + .NET Core SDK build 5.0.102: Fail
4) App Re-Target 6.0 + .NET Core SDK build 6.0.100-preview.1.21080.2: Fail

**Repro steps**
Source code is targeting netcoreapp3.1(default Runtime) , global.json set to 6.0.100-preview.1.21080.2
1) Source Code check: [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1272682](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1272682)
2) dotnet build

**Expected Result:**
Build succeeded

**Actual Result:**
```
C:\Users\valtunc\Desktop\Sources\DiscordChatExporter\DiscordChatExporter.Gui\ViewModels\Framework\DialogScreen.cs(13,44): error CS8601: Possible null reference assignment. [C:\Users\valtunc\Desktop\Sources\DiscordChatExporter\DiscordChatExporter.Gui\DiscordChatExporter.Gui_nlgh5as3_wpftmp.csproj]
Build FAILED.
```

**Findings:**
Since we are not changing default target(3.1), we think it should build successfully with net6 SDK(build succeeded with net5 SDK)
When we target to net5 or net6, we get issues related to nullable, to resolve nullable issues, we need to remove 
```
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
```
inside Directory.Build.props file. 
But with the config above, we need to understand the different behaviors of default target 3.1 build with .NET 5 & .NET 6, and retarget 5 & 6 both failed.
```
1) App Target 3.1 + .NET Core SDK build 6.0.100-preview.1.21080.2: Fail
2) App Target 3.1 + .NET Core SDK build 5.0.102: Pass
3) App Re-Target 5.0 + .NET Core SDK build 5.0.102: Fail
4) App Re-Target 6.0 + .NET Core SDK build 6.0.100-preview.1.21080.2: Fail
```

@dotnet-actwx-bot  @dotnet/compat

**Comment by jiangzeng01** [comment]
@ryalanms Thanks Ryland for investigation! I moved the issue to Roslyn

**Comment by jiangzeng01** [comment]
@cston According to your PR [https://github.com/dotnet/roslyn/issues/46044](https://github.com/dotnet/roslyn/issues/46044), there are new warnings when nullable enabled, and would turn into errors when WarningsAsErrors  enabled. 
It will cause some 3.1 apps failed to build with .NET 6 SDK. (this ticket).
Do you have breaking change document for this new change for .NET 6?

**Comment by cston** [comment]
Thanks for reporting @jiangzeng01. I've added this to a new "Compiler Breaking Changes - post .NET 5.md".

**Comment by jiangzeng01** [comment]
@cston Thanks a lot!
