### ISSUE TITLE
"CS8306: Tuple element name inferred" reported for conversion

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#21518]
Compile with language version 7.0 with 7.1 compiler:
```
class C
{
    static void F((object, object) t)
    {
    }
    static void G(object o)
    {
        var t = (1, o);
        F(t);
    }
}
```
`(9,11): error CS8306: Tuple element name 'o' is inferred. Please use language version 7.1 or greater to access an element by its inferred name.`

**Comment by tlycken** [comment]
I'm seeing this too:

```
GetIrrelevantCollection()
.Select(g =>
{
    // do irrelevant stuff that, among other things, define the variables used below
    return (g.Key, (teama, teamb));
})
.Select(data => {
    (var round, var bids) = data; // this line fails to compile
```

**Comment by kellypleahy** [comment]
I'm seeing this as well...

```
 foreach (var (gr, i) in _testInput.Select((x, i) => (x, i)))
                arrayizeGroup.ProcessInput(gr, "filtersumhash", i, cohortWeights);
```

**Comment by jcouv** [comment]
This was fixed in 15.3.2

**Comment by user135711** [comment]
@jcouv @cston I am still getting this error on 15.5.3 unless I compile with C# latest minor version. Was that the behavior intended or is this still a bug?

**Comment by jcouv** [comment]
@user135711 Could you share details on your current repro? Thanks

**Comment by jcouv** [comment]
@user135711 Without some additional details, I won't be able to make progress on this. It has not repro'ed in my experiments. Please help with VS version number and code sample, if you can. Thanks

**Comment by user135711** [comment]
Sorry, I meant to reply but was busy with something else. Let me see if I
can reproduce the steps now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by user135711** [comment]
I'm on VS 15.5.3
Create a new project C# console .NET application
Replace the line "Console.WriteLine("Hello World!");"
With the following 2 lines (a tuple name projection introduced in C# 7.1):
            var projections = (ToString, one, Item1);
            Console.WriteLine(projections.one);

The error is as noted:
Severity Code Description Project File Line Suppression State
Error CS8306 Tuple element name 'one' is inferred. Please use language
version 7.1 or greater to access an element by its inferred name.
TestConsoleApp2 C:\Users\blah\Documents\Visual Studio
2017\Projects\TestConsoleApp2\TestConsoleApp2\Program.cs 85 Active

The fix is in the error so I don't know if this is actually a bug: Go to
project properties, build, advanced, change Language Version from Major to
C# 7.1,7.2 or latest minor.

**Comment by user135711** [comment]
You can close this. I misunderstood the bug. The error doesn't occur when you use 7.1 or higher as it should according to the docs: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#Language version selection

**Comment by jcouv** [comment]
Glad this is resolved. I'll go ahead and close. Cheers
