### PR TITLE
Add AttributeUsage to EmbeddedAttribute

### PR DESCRIPTION
**Pull request by michha**
prevents warning _CA1018: Specify AttributeUsage on EmbeddedAttribute_

EmbeddedAttribute was introduced in #76583

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Comment by michha** [comment]
@333fred could you please assist me with this error?

Build https://dev.azure.com/dnceng-public/public/_build/results?buildId=1125466&view=logs&j=644ea285-4692-54f6-2965-667c9562a0e2&t=b2948985-b3d8-5780-7b2b-b582fd83c893&l=97 failed with

```
  Failed Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.SourceGeneration.GeneratorDriverTests.IncrementalGenerator_PostInit_AddEmbeddedAttributeSource_Adds [17 ms]
  Error Message:
   
Expected:
Actual:
                // /datadisks/disk1/work/A3BA09A1/t/RoslynTests/Microsoft.CodeAnalysis.Test.Utilities/Roslyn.Test.Utilities.TestGenerators.PipelineCallbackGenerator2/Microsoft.CodeAnalysis.EmbeddedAttribute.cs(3,6): error CS0579: Duplicate 'global::System.AttributeUsage' attribute
                //     [global::System.AttributeUsage(global::System.AttributeTargets.All)]
                Diagnostic(ErrorCode.ERR_DuplicateAttribute, "global::System.AttributeUsage").WithArguments("global::System.AttributeUsage").WithLocation(3, 6)
Diff:
++>                 Diagnostic(ErrorCode.ERR_DuplicateAttribute, "global::System.AttributeUsage").WithArguments("global::System.AttributeUsage").WithLocation(3, 6)
  Stack Trace:
     at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly) in /_/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs:line 99
   at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected) in /_/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs:line 48
   at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected) in /_/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs:line 63
   at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected) in /_/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs:line 109
   at Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.SourceGeneration.GeneratorDriverTests.IncrementalGenerator_PostInit_AddEmbeddedAttributeSource_Adds() in /_/src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs:line 2537
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by 333fred** [comment]
Ah right, this is not possible; if multiple generators add the attribute, they'll each have `AttributeUsage`. This approach cannot be taken.

Likely what we should do is mark the generated file as generated, by including an `// <auto-generated/>` at the top. Let's do that in a separate PR.
