### ISSUE TITLE
After upgrading "Microsoft.CodeAnalysis.CSharp" from 4.2.0 to 4.30 generator errors

### ISSUE THREAD

**Issue by Phylum123** [dotnet/roslyn#64323]
If I upgrade my source generators from 4.2.0 to 4.30, then all of the projects using the source generator will not compile, complaining that the source generator is not generating source (it is generating, just fine). As a consequence any errors caused by the source not being generated (in my case a missing constructor) will cause it to not compile. The weird part is, there are no errors in the errors list, you have to look at the build output to see  the issue. If I downgrade back to 4.2.0, everything works fine.

5>CSC : warning CS8785: Generator 'ContextGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
5>C:\Users\JTower\source\repos\Pario2NewModel\CIIS.Pario2.Approvals.Shared\ApprovalRemoteContext.cs(13,26,13,47): error CS7036: There is no argument given that corresponds to the required formal parameter 'connection' of 'ContextBase.ContextBase(ConnectionWrapper, IMessageParser, ContextOptions)'
5>Done building project "CIIS.Pario2.Approvals.Shared.csproj" -- FAILED.
========== Rebuild All: 4 succeeded, 1 failed, 0 skipped ==========

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/63921

**Comment by RikkiGibson** [comment]
This is fixed in the upcoming VS patch (17.3.5).
