### ISSUE TITLE
vs2022 not working with sdk 7.0.100

### ISSUE THREAD

**Issue by pedoc** [dotnet/roslyn#64704]
**Version Used**: 
visual studio 2022 17.3.6
.net sdk 7.0.100 download from https://github.com/dotnet/installer#table,[link](https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe)

**Steps to Reproduce**:

1. open visual studio,create new console project
2. build it

will generate the following compilation error
``CS0518`` ``NU1102`` etc
![image](https://user-images.githubusercontent.com/6604230/195581317-3c57ee54-c2fb-413d-bc15-c688b9f6ba93.png)

The same error also occurs when compiling directly from the command line``dotnet run``：
![image](https://user-images.githubusercontent.com/6604230/195581770-f30795e1-9bae-4018-91fe-8afc5f056a27.png)

But if you use ··global.json·· to specify a specific version, it compiles correctly from the command line
```
dotnet new globaljson --sdk-version 6.0.402
dotnet run
```
![image](https://user-images.githubusercontent.com/6604230/195582120-968a0ddb-9d71-4c56-a524-4330cc9180e0.png)

Even so, I still get the same error when compiling in VS. So, why does vs not respect ``global.json``?
Currently, only after uninstalling 7.0.100sdk can it be successfully compiled in VS, which is the only way at present.

PS:
If the location of this question is not correct, please help forward to the correct location, thanks

**Expected Behavior**:
Compiles correctly
**Actual Behavior**:
Compilation failed

**Comment by huoyaoyuan** [comment]
The nightly SDK is requiring version `6.0.11` of reference assemblies of .NET 6. However, the latest version is `6.0.10` which was released 3 days ago.

Do you currently have 6.0 SDK installed too?

Does changing "use preview SDK" setting in VS have any effect?

Personally, I would recommend installing monthly preview/RC versions instead of nightly versions.
