### PR TITLE
Fix build break.

### LINKED ISSUE #46302: Build break in master
```none
R:\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageClient\InProcLanguageServer.cs(155,16): error CS0103: The na
me '_protocol' does not exist in the current context [R:\roslyn\src\VisualStudio\Core\Def\Microsoft.VisualStudio.Langua
geServices_z3ntnm0v_wpftmp.csproj]
R:\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageClient\InProcLanguageServer.cs(160,16): error CS0103: The na
me '_protocol' does not exist in the current context [R:\roslyn\src\VisualStudio\Core\Def\Microsoft.VisualStudio.Langua
geServices_z3ntnm0v_wpftmp.csproj]
R:\roslyn\src\VisualStudio\Core\Def\Implementation\LanguageClient\InProcLanguageServer.cs(216,16): error CS0103: The na
me '_protocol' does not exist in the current context [R:\roslyn\src\VisualStudio\Core\Def\Microsoft.VisualStudio.Langua
geServices_z3ntnm0v_wpftmp.csproj]
    0 Warning(s)
    3 Error(s)
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #46302

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-infrastructure May I please have a review? This fixes a semantic merge conflict that github didn't notice.

**Comment by jaredpar** [comment]
The CI legs have made it past the build phase. Merging as this is fixing an urgent build break. Getting past build unblocks everything else.
