### ISSUE TITLE
Regression - nullable suppression doesn't fix nullability exhaustiveness warnings in switches over tuple expressions

### ISSUE THREAD

**Issue by TessenR** [dotnet/roslyn#51904]
**Version Used**: 
```
Branch main (12 Mar 2021)
Latest commit 8da536d by msftbot[bot]:
Merge pull request #51811 from CyrusNajmabadi/simplifyCompletion

Simplify portions of symbol completion
```

**Steps to Reproduce**:

Compile the following code
```cs
#nullable enable
public class C {
  public int M1(C? a) => a! switch { C _ => 0 }; // no warnings
  public int M2(C? a) => (1, a!) switch { (_, C _) => 0 }; // CS8655
  
  // to demonstrate that it cannot be suppressed at all
  public int M3(C? a) => (1, a!)! switch { (_, C _) => 0 }; // CS8655
  public int M4(C? a) => (1, a!)! switch { (_, C _) => 0 }!; // CS8655; error CS1519 (invalid suppression)
}
```

**Expected Behavior**:
No warnings in both `M1` and `M2` since in both cases the input expressions for `C _` pattern are explicitly suppressed and thus shouldn't contain null values

**Actual Behavior**:
The suppression expression works for `M1` but not for `M2`;
`M2` reports incorrect `CS8655: The switch expression does not handle some null inputs (it is not exhaustive). For example, the pattern '(_, null)' is not covered.`

**Notes**
This problem makes it impossible to suppress the CS8655 warning claiming that the `null` input is not handled since suppressing warnings for the whole input tuple expression doesn't work either and placing a suppression on the switch itself is illegal (see `M3` and `M4`)

Note that this is a regression in VS16.10 preview as the suppression works correctly in VS16.9.0

This might be related to https://github.com/dotnet/roslyn/issues/51853 - see the Notes section; Nullable analysis doesn't properly obtain an input expression for tuple components and doesn't check if they are suppressed as it does for the governing expression itself (e.g. in `VisitSwitchExpressionCore` - `int slot = node.Expression.IsSuppressed ? GetOrCreatePlaceholderSlot(node.Expression) : MakeSlot(node.Expression);`

[jcouv: note to self, using branch `switch-suppression` to investigate this]
