### ISSUE TITLE
IDE0017 suggestion breaks on field cross-reference

### ISSUE THREAD

**Issue by hseg** [dotnet/roslyn#59576]
**Version Used**:
Visual Studio Community 2022, 17.0.6
**Steps to Reproduce**:

Use the autosuggested fix for IDE0017 on
```C#
var x = new C();
x.A = a;
x.B = x.A;
```
**Expected Behavior**:

One of:
- No suggestion
- Suggest the maximal safe refactor, ie
  ```C#
  var x = new C { A = a};
  x.B = x.A;
  ```
- The semantics expected by the rewrite to be valid, i.e. referring to the object being initialized from within the initializer is permitted

**Actual Behavior**:

```C#
var x = new C
{
  A = a,
  B = x.A
};
```
This causes a `NullReferenceException`, since the `B` initialization refers to the uninitialized `x` variable (at least, if the semantics described [here](https://web.archive.org/web/20190628081025/http://community.bartdesmet.net/blogs/bart/archive/2007/11/22/c-3-0-object-initializers-revisited.aspx) are to be believed)

**Comment by hseg** [comment]
Correction: @Suchiman on #csharp tried to reproduce this for the snippet posted and got a `error CS0841: Cannot use local variable 'x' before it is declared` warning.
Checking my initial code, the full context is
```C#
var x = TryGetX();
if (x is null)
{
   x = new X();
   x.A = a;
   x.B = x.A;
}
```
And indeed, if I try the snippet as I posted it I get `error CS0165: Use of unassigned local variable 'x'`.

So the issue is a little more nuanced than I initially thought -- the transformation is incorrect since it replaces an assignment referring to `x.A`'s new value to `x.A`'s old value. Which _would_ cause an error if the declaration was in the same line as the initialization, but since in my code they are separated, it appears to the compiler that everything is in order, while silently changing the semantics of the code.

**Comment by hseg** [comment]
Should note: I am working with C# 7.3, so a backport would be appreciated

**Comment by CyrusNajmabadi** [comment]
Yup.  We now generate: 

![image](https://user-images.githubusercontent.com/4564579/154373379-e18ad0cc-724a-4e9b-8642-e0aa3cb3f94a.png)

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/59479.
