### ISSUE TITLE
Build regression between targeting netcoreapp3.1 and net5.0; looks like a compiler bug

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/roslyn#52834]
**Version Used**: 

dotnet --version reports 5.0.202

**Steps to Reproduce**:

Build the attached project [csregression.zip](https://github.com/dotnet/roslyn/files/6359546/csregression.zip)

**Expected Behavior**:

Project builds

**Actual Behavior**:

error CS0165: Use of unassigned local variable 'sv' 

but sv is clearly only used if assigned as ?.TryGetValue() can't possibly be anything other than null unless .TryGetValue() is invoked

Changing the target to netcoreapp3.1 allows the project to build.

**Comment by RikkiGibson** [comment]
Have investigated this a bit this morning.

This is not a scenario that is expected to work in general. i.e. assigning a variable on the right side of a `?.` expression doesn't propagate to outside the `?.` expression. I am working on a feature right now to improve that in C# 10 dotnet/csharplang#4465.

It looks like this scenario works in netcoreapp3.1 because a quirk in the ref assemblies makes us treat this struct as empty, i.e. it is "vacuously" definitely assigned as soon as it is declared, since after all, all zero of its fields are definitely assigned.

I didn't debug closely with net5.0 but most likely a difference in the ref assemblies cause us to treat this struct as non-empty.

**Comment by jhudsoncedaron** [comment]
Well that explains why I couldn't reduce out asp.net from the reproduction anyway.

You know, sometimes I'd rather just tell the compiler to shut up and assume something's initialized. I've got a couple dozen cases where something is definitely initialized but the compiler can't prove it. This one's special because as an out declaration, I can't throw = default on it to tell the compiler to shut up.

Note that I've constructed cases where the out variable wasn't initialized despite the method being called, so the compiler is making an assumption anyway.

**Comment by RikkiGibson** [comment]
>Note that I've constructed cases where the out variable wasn't initialized despite the method being called, so the compiler is making an assumption anyway.

Could you elaborate on this?

**Comment by jhudsoncedaron** [comment]
Something along the lines of
````
Guid LookupProcessGuid(IDictionary<string, Guid> source)
{
    Guid value = new Guid("01234567-89AB-CDEF-0123456789AB");
    source.TryGetValue("process", out value);
    return value;
}
````

The implementation of the normal IDictionary wasn't in C# and didn't know what `out` was. On passing a stock Dictionary in, chaos ensued as the default value wasn't being returned (which was the most common case).

**Comment by RikkiGibson** [comment]
Makes sense, thanks.

I can't speak to whether the language would introduce a way to suppress definite assignment diagnostics. It may be worth starting a conversation in csharplang.

I think "By Design" is an accurate resolution here, since the compiler is behaving the way we expect, it's just that our "compat mode" of analysis for structs ends up causing confusion.
