### ISSUE TITLE
`UnscopedRef` should not affect code under the old ref safety rules

### ISSUE THREAD

**Issue by jjonescz** [dotnet/roslyn#75828]
**Version Used**: .NET 9 RC2

**Steps to Reproduce**:

Compile with C# 10 and TFM net6.0:

```cs
struct S
{
    public int F;

    [UnscopedRef] public ref int Ref() => ref F;
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
    public sealed class UnscopedRefAttribute : Attribute
    {
    }
}
```

**Expected Behavior**: Error at `ref F` same as if the UnscopedRef attribute wasn't present, because the code should use [the old ref safety rules](https://github.com/dotnet/csharplang/blob/8e11f7b7fe1f79adcf02d015b92a8361de63856e/proposals/csharp-11.0/low-level-struct-improvements.md#refsafetyrulesattribute) when compiled with C# 10 and TFM net6.0.

```
error CS8170: Struct members cannot return 'this' or other instance members by reference
```

**Actual Behavior**: No errors.
