### PR TITLE
clean up and refactoring around global assets.

### PR DESCRIPTION
**Pull request by heejaechang**
now, it will get synched when remote host is first created rather than doing that on demand. No functionality change, just re-organized where things happening.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @panopticoncentral can you take a look?

tagging @KevinH-MS @CyrusNajmabadi @rynowak FYI.

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
ping? I need this change for my next PR. can someone take a look?

**Comment by jmarolf** [comment]
@heejaechang looks like this broke the build
```
Services\ServiceHubServicesTests.cs(66,56): error CS0117: 'TestWorkspace' does not contain a definition for 'CreateCSharpAsync' [C:\source\roslyn\Open\src\VisualStudio\Core\Test.Next\VisualStudioTest.Next.csproj]
```

**Comment by heejaechang** [comment]
@jmarolf @rchande just checked in the fix.

**Comment by jasonmalinowski** [comment]
How did this break? Did it cross with one of @CyrusNajmabadi's changes? (no fault to both of you, just want to understand what happened)

**Comment by heejaechang** [comment]
@jasonmalinowski it didn't show any merge conflict and tests were all green so I checked in.

**Comment by jasonmalinowski** [comment]
@heejaechang Was this just a situation where your change and @CyrusNajmabadi's were both green in isolation but broke when combined?

**Comment by heejaechang** [comment]
@jasonmalinowski yep. I added a test which uses TestWorkspace and Cyrus change changed Create method of TestWorkspace.
