### ISSUE TITLE
Upgrading to 17.13 causes CS0023 errors when using Linq

### ISSUE THREAD

**Issue by kenbreid** [dotnet/roslyn#77212]
When updating Visual Studio from 17.12.4 to 17.13.0, we're seeing some previously working code now failing to compile.

We have a couple patterns similar to the following (with addr being a System.Net.IPAddress type and a using statement for System.Linq):

`BitArray ipAddressBits = new BitArray(addr.GetAddressBytes().Reverse().ToArray());`

While that would compile successfully when using 17.12.4, it fails after updating to 17.13.0 with the following:

error CS0023: Operator '.' cannot be applied to operand of type 'void'

**Comment by RikkiGibson** [comment]
Do you have `<LangVersion>preview</LangVersion>` in your project? That can cause you to be subject to the break detailed here:

https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%2010.md#spant-and-readonlyspant-overloads-are-applicable-in-more-scenarios-in-c-14-and-newer

> When using C# 14 or newer and targeting a .NET older than `net10.0`
> or .NET Framework with `System.Memory` reference,
> there is a breaking change with `Enumerable.Reverse` and arrays:
> 
> ```cs
> int[] x = new[] { 1, 2, 3 };
> var y = x.Reverse(); // previously Enumerable.Reverse, now MemoryExtensions.Reverse
> ```
> 
> On `net10.0`, there is `Enumerable.Reverse(this T[])` which takes precedence and hence the break is avoided.
> Otherwise, `MemoryExtensions.Reverse(this Span<T>)` is resolved which has different semantics
> than `Enumerable.Reverse(this IEnumerable<T>)` (which used to be resolved in C# 13 and lower).
> Specifically, the `Span` extension does the reversal in place and returns `void`.
> As a workaround, one can define their own `Enumerable.Reverse(this T[])` or use `Enumerable.Reverse` explicitly:
> 
> ```cs
> int[] x = new[] { 1, 2, 3 };
> var y = Enumerable.Reverse(x); // instead of 'x.Reverse();'
> ```

**Comment by kenbreid** [comment]
Double checking all the impacted projects, those are importing a props chain that does set a preview LangVersion. I also confirmed these are all targeting older framework versions.

Thanks for the pointer, and I'll work with our impacted teams to get everything updated accordingly.

**Comment by RikkiGibson** [comment]
Sounds good, feel free to follow up here if you had further questions or concerns.
