### ISSUE TITLE
Full signing is broken again on Mono with Roslyn 2.8

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/roslyn#26678]
**Version Used**: Roslyn 2.8.0 (e595ee27)

The regression was introduced with https://github.com/dotnet/roslyn/commit/e2fc8d5ea7d155519eee965354629cb48c6b6ae7 / PR #25426.

**Steps to Reproduce**:

1. Try using full signing on Mono on Unix: `csc /keyfile:mykey.snk Program.cs`
2. It prints an mscoree.dll error

**Expected Behavior**:

No error.

**Actual Behavior**:

```
error CS7027: Error signing output with public key from file 'mykey.snk' -- mscoree.dll
```

---

The new managed signing needs to be enabled when running on Mono too, not just on CoreCLR.

/cc @agocke

**Comment by marek-safar** [comment]
@jaredpar this is another regression on our side, could you guys address it shortly.

**Comment by agocke** [comment]
Fixed by #26683
