### ISSUE TITLE
AssemblyInformationalVersionAttribute needs to allow NuGet versions

### ISSUE THREAD

**Issue by eerhardt** [dotnet/roslyn#11529]
**Version Used**: 1.3.0-beta1-20160523-03

**Steps to Reproduce**:

1. [assembly:System.Reflection.AssemblyInformationalVersionAttribute("1.0.0-rc3")]
2. build

**Expected Behavior**:
The build should succeed.

**Actual Behavior**:
C:\cli\src\Microsoft.DotNet.InternalAbstractions\obj\Debug\netstandard1.3\dotnet-compile.assemblyinfo.cs(5,67): error CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision

**Notes**

I believe this regression was caused by #10620.

The dotnet/cli generates an AssemblyInformationalVersionAttribute using the "version" property in the project.json:

{
  "description": "Abstractions for making code that uses file system and environment testable.",
  **"version": "1.0.0-rc3-*",**
  "buildOptions": 

The new behavior of AssemblyInformationalVersionAttribute is breaking this and will cause warnings/errors on every project built with project.json.

This is blocking dotnet/cli from taking a new Roslyn build.

**Comment by gkhanna79** [comment]
This is blocking SharedFW from picking up a new build of Roslyn that is required to fix https://github.com/dotnet/coreclr/issues/5149 which is required to enable Roslyn to load Analyzers in their own load context.

And when this is fixed for the dev branches (of Roslyn and CLI repos), the change needs to make to RTM branches as well.

CC @jkotas
