### ISSUE TITLE
.Select() on IQueryable is seen as the .Select() of IEnumerable and code fails to compile on NETstandard 1.6. 

### ISSUE THREAD

**Issue by FransBouma** [dotnet/roslyn#17704]
**Version Used**: vs 2017 RTM

**Steps to Reproduce**:

1. load attached solution in vs 2017 RTM
2. Build
3. Error in DTO persistence project: `3>SohDtoPersistence.cs(30,21,30,27): error CS0411: The type arguments for method 'Enumerable.Select<TSource, TResult>(IEnumerable<TSource>, Func<TSource, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly`. 

**Expected Behavior**:
Compiling code.

**Actual Behavior**:
Compiler error. 

The code is generated (except for one small hand-added polyfill for SerializableAttribute in another not related class) and when I generated the exact same code for .NET 4.6.1 and compile it (after adding the reference to EF core) it compiles fine. Intellisense there shows correctly, that the .Select() method is of Queryable and not Enumerable. 

See the attached solution for a repro. 
[RoslynBugRepro.zip](https://github.com/dotnet/roslyn/files/834236/RoslynBugRepro.zip)

**Comment by FransBouma** [comment]
PEBKAC! I have to add the reference System.Linq.Queryable, which isn't added by default through the framework. 

No bug. Carry on!
