### ISSUE TITLE
Roslyn cannot delay sign with ECMA key on Linux

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/roslyn#2444]
In https://github.com/dotnet/corefx/pull/1601 I had to work around this by putting a different key on an assembly temporarily. The error you get is the following:

```
CSC : error CS7027: Error signing output with public key from file '/home/jeremy/repos/corefx/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00040/lib/ECMA.snk' -- mscoree.dll [/home/jeremy/repos/corefx/src/System.IO.Compression/src/System.IO.Compression.csproj]
CSC : warning CS7033: Delay signing was specified and requires a public key, but no public key was specified [/home/jeremy/repos/corefx/src/System.IO.Compression/src/System.IO.Compression.csproj]
```
The project in CoreFX that uses this key currently is `corefx/src/System.IO.Compression/src/System.IO.Compression.csproj`. My repro was on CoreFx master with the xplat branch of MSBuild on Mono 3.12.1.

```
mono ~/repos/msbuild/bin/Unix/Debug-MONO/MSBuild.exe -t:Build -fl "-flp:LogFile=msbuild-corefx.log;V=diag;" -p:Configuration=Linux_Debug -p:UseRoslynCompiler=true ~/repos/corefx/src/System.IO.Compression/src/System.IO.Compression.csproj
```

**Comment by JeremyKuhne** [comment]
@jaredpar Here is the signing issue we discussed.

**Comment by tmat** [comment]
We can't fully sign on non-Windows platforms. On Windows we are P/Invoking Desktop CLR to do so.
We can however OSS-sign. We already have the functionality mostly implemented internally. Finishing it and exposing it thru csc.exe is tracked by this workitem: #1171.

If you need to fully sign an assembly, please file a bug on CoreFx to provide API to do so.

**Comment by JeremyKuhne** [comment]
@tmat How do we get the full name in the assembly in this case in the meantime, eg: b77a5c561934e089?

**Comment by tmat** [comment]
We could perhaps provide some temporary solution in the coreclr branch. E.g. /feature:publicKey=file_with_raw_public_key
 
/cc @theoy @jaredpar

**Comment by jaredpar** [comment]
Resolving as "won't fix" for now.  Roslyn has always used CLR for full and delay signing.  Until there is a bug tracking adding that in a cross platform fashion there is nothing Roslyn can do here.  Should that become available though, we'd keen on adding that support.

Note: public signing cross platform will be in 1.2 (already in master).

**Comment by ellismg** [comment]
@jaredpar What commit adds public signing support?

**Comment by jaredpar** [comment]
The best commit to look at is: https://github.com/dotnet/roslyn/commit/58b3d354d1c616355952dd9b3af9e72505a2f7af  This is the last bug fix we applied to public signing.  It will have the compiler and MSBuild support.
