### ISSUE TITLE
Inference failure for tuple type vs tuple underlying type (regression)

### ISSUE THREAD

**Issue by gafter** [dotnet/roslyn#20583]
The following correct program compiles successfully in VS2015, but fails to compile in VS2017:

``` c#
using System;
public class C
{
    public static void Main()
    {
        // var b = (1, 2, 3, 4, 5, 6, 7, 8);
        var b = new ValueTuple<int, int, int, int, int, int, int, ValueTuple<int>>(1, 2, 3, 4, 5, 6, 7, new ValueTuple<int>(8));
        M1(b);
    }
    public static void M1<T1, T2, T3, T4, T5, T6, T7, TRest>(ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest> a) where TRest : struct { Console.Write(1); }
}
```

with the following error

``` none
Error CS0411: The type arguments for method 'C.M1<T1, T2, T3, T4, T5, T6, T7, TRest>(ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

**Comment by gafter** [comment]
A regression test is being added for this (skipped) in #20587.

**Comment by gafter** [comment]
I did not test whether or not this bug is present for VB.

**Comment by gafter** [comment]
This bug is present for VB as well. The following program compiles in earlier versions of VS, but not in VS 2017.

``` vb
Public Class C
    Public Shared Sub Main()
        Dim b = New ValueTuple(Of Integer, Integer, Integer, Integer, Integer, Integer, Integer, ValueTuple(Of Integer))()
        M1(b)
    End Sub
    Public Shared Sub M1(Of T1, T2, T3, T4, T5, T6, T7, TRest As Structure)(x As ValueTuple(Of T1, T2, T3, T4, T5, T6, T7, TRest))
    End Sub
End Class
```

**Comment by gafter** [comment]
This would likely be fixed as a side-effect of https://github.com/dotnet/roslyn/issues/20648
