### PR TITLE
Fix ALC in ProjectReference scenarios

### LINKED ISSUE #56442: RC1 regression: dependencies no longer work correctly in source generators across <ProjectReference>
When using a source generator via a `<ProjectReference>` inside a solution, and when the source generator needs to have dependencies, the solution documented by @sharwell [here](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145) can be used. Unfortunately, while this still worked in 6.0.0-preview.7, it no longer seems to work in 6.0.0-rc.1.

For a minimal repro, see https://github.com/roji/Test/tree/SourceGeneratorRc1. Building that solution works in preview7, but in rc1 I'm getting the following:

```
CSC : warning CS8785: Generator 'NpgsqlConnectionStringBuilderSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'Scriban.Signed, Version=4.0.1.0, Culture=neutral, PublicKeyToken=5675fb69b15f2433'. The system cannot find the file specified. [/home/roji/projects/test/Test/Test.csproj]
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #56442 

cc @jaredpar @chsienki

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs [hunk 1]
```diff
@@ -136,14 +138,35 @@ public DirectoryLoadContext(string directory, DefaultAnalyzerAssemblyLoader load
...
+                    var candidateName = AssemblyName.GetAssemblyName(candidatePath);
+                    // checking FullName ensures that version and PublicKeyToken match exactly
+                    if (candidateName.FullName.Equals(assemblyName.FullName, StringComparison.OrdinalIgnoreCase))
+                    {
+                        return LoadFromAssemblyPath(_loader.GetPathToLoad(candidatePath));
+                    }
+                }
+
+                // None of the candidate paths contained a compatible version of the assembly.
+                return null;
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:162]: Think this should be some version of `throw` here. Essentially it's not going to load into the compiler ALC, it's not a dependency so this should affirmatively fail. By `returning null` here you open the potential for the Default ALC to satisfy the dependency hence which is unexpected.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs [hunk 2]
```diff
@@ -136,14 +138,35 @@ public DirectoryLoadContext(string directory, DefaultAnalyzerAssemblyLoader load
...
+
+                // The assembly isn't expected to be found at 'assemblyPath',
+                // but some assembly with the same name is known to the loader.
+                foreach (var candidatePath in paths)
+                {
+                    // Note: we assume that the assembly really can be found at this path,
+                    // and that calling GetAssemblyName doesn't cause us to hold a lock on the file
+                    var candidateName = AssemblyName.GetAssemblyName(candidatePath);
+                    // checking FullName ensures that version and PublicKeyToken match exactly
+                    if (candidateName.FullName.Equals(assemblyName.FullName, StringComparison.OrdinalIgnoreCase))
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:155]: This could cause unexpected behavior. Consider for example if the analyzer had a reference to C at version 2. Now consider a scenario where other analyzers provide version 1 and version 3. It's a toss up to which would get loaded here. I think we should be considering the `AssemblyName` in the list here and then preferring an exact match first and lacking that use the highest available version.

Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:155]: This FullName includes the version and therefore requires an exact match. I could replace it with explicit comparisons of the name, version and PKT if you prefer.

I think the described scenario is covered by one of the new tests.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:162]: I think you're correct. I'll add a test.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:159]: I misinterpreted the comment at first. Have now addressed the concern by searching for the candidate with the highest version.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs]: Fixed.

**Comment by jaredpar** [comment]
@chsienki, @cston PTAL

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 3]
```diff
@@ -203,6 +225,166 @@ public void AssemblyLoading_MultipleVersions()
...
+
+#if NETCOREAPP
+            var alcs = DefaultAnalyzerAssemblyLoader.TestAccessor.GetOrderedLoadContexts(loader);
+            Assert.Equal(1, alcs.Length);
+
+            Assert.Equal(new[] {
+                ("Delta", "1.0.0.0", delta1File.Path),
+                ("Epsilon", "0.0.0.0", epsilonFile.Path)
+            }, alcs[0].Assemblies.Select(a => (a.GetName().Name!, a.GetName().Version!.ToString(), a.Location)).Order());
+#endif
```
Comment (cston) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:379]: Consider extracting a helper method: `VerifyLoadContexts(new[] { ("Delta", ..., ...), ("Epsilon", ..., ...) });`

**Review by cston — APPROVED** [review]

**Review by chsienki — APPROVED** [review]

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 4]
```diff
@@ -150,6 +150,28 @@ public void AssemblyLoading_DependencyLocationNotAdded()
...
+            loader.AddDependencyLocation(deltaFile.Path);
+            loader.AddDependencyLocation(_testFixture.Gamma.Path);
+            Assembly gamma = loader.LoadFromPath(_testFixture.Gamma.Path);
+
+            var b = gamma.CreateInstance("Gamma.G")!;
+            var writeMethod = b.GetType().GetMethod("Write")!;
+            writeMethod.Invoke(b, new object[] { sb, "Test G" });
+
+            var actual = sb.ToString();
+            Assert.Equal(@"Delta: Gamma: Test G
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:171]: You're asking which copy of Delta version 1, right? I think we can check what file paths the assemblies were loaded from using the TestAccessor, but I'd have to check.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:397]: Done
