### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp 4 doesn't work on .NETStandard 2.0

### ISSUE THREAD

**Issue by Serg046** [dotnet/roslyn#59515]
**Version Used**: 
4.0.1

**Steps to Reproduce**:
The issue is visible in the following PR and AppVeyor job:
https://github.com/Serg046/AutoFake/pull/203
https://ci.appveyor.com/project/Serg046/autofake/builds/42409641
So everything is working with 3.11.0 but not with 4.0.1.

```
Analyzers -> C:\projects\autofake\Analyzers\bin\Release\netstandard2.0\Analyzers.dll
CSC : error CS8032: An instance of analyzer Analyzers.Analyzer cannot be created from C:\projects\autofake\Analyzers\bin\Release\netstandard2.0\Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. 
```

**Comment by Youssef1313** [comment]
@Serg046 What version of the .NET SDK are you using? CodeAnalysis 4.x is compatible with .NET 6.0 SDK (and Visual Studio 2022)

**Comment by Serg046** [comment]
Thank you, it helped
