### ISSUE TITLE
Constant Expression implicit shortening conversion regression with ternary operator.

### ISSUE THREAD

**Issue by willson556** [dotnet/roslyn#52099]
**Version Used**:  Reproduced with both VS 16.9.2 and SharpLab `main (22 Mar 2021)`

**Steps to Reproduce**:

Compile the following C# code (e.g. using SharpLab):
```cs
using System;
public class C {
    public void M() {
        bool test = false;
        short a = test ? 1 : 0;
    }
}
```

**Expected Behavior**: 

Successful compilation (based on https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#implicit-constant-expression-conversions)

**Actual Behavior**: 

```
error CS0266: Cannot implicitly convert type 'int' to 'short'. An explicit conversion exists (are you missing a cast?)
```
The above successfully compiles in VS 16.8.2, 16.8.4, & 16.7.13 as well as the `Default` environment on SharpLab (as of 2021-03-23, not sure when they'll update the default environment).

**Comment by cston** [comment]
Thanks for reporting this @willson556.

The error is expected. The expression was incorrectly treated as target-typed in 16.8. 

A target-typed conditional expression conversion should only be used when there is no common type between the sub-expressions - see [conditional-expression-conversion](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/target-typed-conditional-expression.md#conditional-expression-conversion).

See #49598. The breaking change was documented in #51754.

**Comment by willson556** [comment]
Ah, okay -- wasn't aware of that document, will look out for that in the future.

Thanks for your help!
