### ISSUE TITLE
MSBuildWorkspace throwing "We expected a non-null result but got null back"

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn#83724]
> Updated Microsoft.CodeAnalysis.Workspaces.MSBuild to 5.8.0-1.26257.103, along with same version for Microsoft.CodeAnalysis.Workspaces.Common, Microsoft.CodeAnalysis.Workspaces.MSBuild.Contracts, Microsoft.CodeAnalysis.VisualBasic.Workspaces, Microsoft.CodeAnalysis.VisualBasic.Features, Microsoft.CodeAnalysis.Scripting.Common, Microsoft.CodeAnalysis.CSharp.Features, Microsoft.CodeAnalysis.CSharp, Microsoft.CodeAnalysis.Compilers, Microsoft.CodeAnalysis.Common. etc. But got other exceptions when calling OpenSolutionAsync().Result from an instance of MSBuildWorkspace like below
> 
> ```
> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: We expected a non-null result but got null back. - file RpcClient.cs line 136
>    at Microsoft.CodeAnalysis.Contract.Fail(String message, Int32 lineNumber, String filePath) in /_/src/roslyn/src/Dependencies/Contracts/Contract.cs:line 161
>    at Microsoft.CodeAnalysis.Contract.ThrowIfNull[T](T value, String message, Int32 lineNumber, String filePath) in /_/src/roslyn/src/Dependencies/Contracts/Contract.cs:line 62
>    at Microsoft.CodeAnalysis.MSBuild.RpcClient.<InvokeAsync>d__14`1.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/Rpc/RpcClient.cs:line 137
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.RemoteBuildHost.<LoadProjectFileAsync>d__6.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/Rpc/RemoteBuildHost.cs:line 50
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.ProjectLoadProgressExtensions.<DoOperationAndReportProgressAsync>d__1`1.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/ProjectLoadProgressExtensions.cs:line 24
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.BuildHostProjectFileInfoProvider.<LoadProjectFileInfosAsync>d__5.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/BuildHostProjectFileInfoProvider.cs:line 28
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__17.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.Worker.cs:line 144
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__16.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.Worker.cs:line 115
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadInfoAsync>d__32.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 284
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadInfoAsync>d__32.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 284
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__30.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 187
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__27.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildWorkspace.cs:line 213
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at our own code of calling instance of MSBuildWorkspace like 'workspace.OpenSolutionASync(solutionPath).Result;'
> ---> (Inner Exception #0) System.InvalidOperationException: We expected a non-null result but got null back. - file RpcClient.cs line 136
>    at Microsoft.CodeAnalysis.Contract.Fail(String message, Int32 lineNumber, String filePath) in /_/src/roslyn/src/Dependencies/Contracts/Contract.cs:line 161
>    at Microsoft.CodeAnalysis.Contract.ThrowIfNull[T](T value, String message, Int32 lineNumber, String filePath) in /_/src/roslyn/src/Dependencies/Contracts/Contract.cs:line 62
>    at Microsoft.CodeAnalysis.MSBuild.RpcClient.<InvokeAsync>d__14`1.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/Rpc/RpcClient.cs:line 137
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.RemoteBuildHost.<LoadProjectFileAsync>d__6.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/Rpc/RemoteBuildHost.cs:line 50
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.ProjectLoadProgressExtensions.<DoOperationAndReportProgressAsync>d__1`1.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/ProjectLoadProgressExtensions.cs:line 24
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.BuildHostProjectFileInfoProvider.<LoadProjectFileInfosAsync>d__5.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/BuildHostProjectFileInfoProvider.cs:line 28
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__17.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.Worker.cs:line 144
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__16.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.Worker.cs:line 115
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadInfoAsync>d__32.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 284
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadInfoAsync>d__32.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 284
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__30.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildProjectLoader.cs:line 187
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__27.MoveNext() in /_/src/roslyn/src/Workspaces/MSBuild/Core/MSBuild/MSBuildWorkspace.cs:line 213<---
> ```
> Same exception occurred for versions of 5.8.0-1.26256.5 and 5.5.0-2.26224.1.
> Test environment
> - .NET Framework 4.8
> - VS 2026 18.2.1 (sonce the 18.5.2 has the known issue, we still use the older version of VS 2026)
> - after upgraded VS 2026 to 18.5.2, the exception still occurred 

 _Originally posted by @awesome-liuxiao in [#82931](https://github.com/dotnet/roslyn/issues/82931#issuecomment-4427500595)_

**Comment by jasonmalinowski** [comment]
@awesome-liuxiao: there's some internal logging code it might be helpful for you to try connecting to. Unfortunately it's internal so we'll need to use reflection to get to it. Try something like this, where you could change the implementation of that "Log" method to write wherever you need to. We will create different loggers with different category names so if you need to write to a file create it just once in MSBuildTestLoggerProvider .


```
using Microsoft.CodeAnalysis.MSBuild;
using Microsoft.Extensions.Logging;
using System.Reflection;

MSBuildWorkspace workspace = MSBuildWorkspace.Create();

MethodInfo addLoggerProvider = typeof(MSBuildWorkspace).GetMethod(
    "AddLoggerProvider",
    BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)!;

addLoggerProvider.Invoke(workspace, [new MSBuildTestLoggerProvider()]);

await workspace.OpenSolutionAsync("F:\\Projects\\Temporary Projects\\MSBuildWorkspaceWithLogging\\MSBuildWorkspaceWithLogging.slnx");

class MSBuildTestLoggerProvider : ILoggerProvider
{
    public ILogger CreateLogger(string categoryName) => new MSBuildTestLogger(categoryName);

    public void Dispose() { }

    private class MSBuildTestLogger : ILogger
    {
        private readonly string _categoryName;

        public MSBuildTestLogger(string categoryName)
        {
            _categoryName = categoryName;
        }

        public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

        public bool IsEnabled(LogLevel logLevel)
        {
            return true;
        }

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)
        {
            Console.WriteLine($"[{_categoryName}] {logLevel}: {formatter(state, exception)}");
            if (exception is not null)
                Console.WriteLine(exception.ToString());
        }
    }
}
```

**Comment by awesome-liuxiao** [comment]
@jasonmalinowski 
First of all, thanks for your assistance.
I've retested my app with the msbuildworkspace 5.8.0-1.26256.5 installed, and changed the package reference approach from packages.config to <PackageReference> in .csproj. Then all of a sudden, the exception disappeared. I also ran a backward compatibility test for VS 2026 18.2.1, and it also ran well. The log you asked for is presented below. I hope this can help.
```
[BuildHost PID 30964] Trace: Message on stderr: info: BuildHost Runtime Version: .NET Framework 4.8.9325.0
[BuildHost PID 30964] Trace: Message on stderr: info: Loading D:\LiuXiao\SureWorkspace\VisualStudioProj\STCS-5161\STCS-5161\STCS-5161.csproj
[BuildHost PID 30964] Trace: Sending a Shutdown request to the BuildHost.
[BuildHost PID 30964] Trace: Message on stderr: info: RPC channel closed; process exiting.
[BuildHost PID 30964] Trace: Process shut down.
[BuildHost PID 40664] Trace: Message on stderr: info: BuildHost Runtime Version: .NET Framework 4.8.9325.0
[BuildHost PID 40664] Trace: Message on stderr: info: Loading D:\LiuXiao\SureWorkspace\VisualStudioProj\STCS-5161\STCS-5161\STCS-5161.csproj
[BuildHost PID 40664] Trace: Sending a Shutdown request to the BuildHost.
[BuildHost PID 40664] Trace: Message on stderr: info: RPC channel closed; process exiting.
[BuildHost PID 40664] Trace: Process shut down.
```
I'm curious that if the current fix is going to be an officially released version, and when it will be released on nuget.org, approximately?

**Comment by awesome-liuxiao** [comment]
@jasonmalinowski 
My apologies for multiple questions.
Another interesting thing was discovered during the backward compatibility test, for earlier Roslyn versions (~5.3), the Project instance generated by MSBuildWorkspace.OpenProjectAsync().Result does not see the compiler-generated files such as App.g.cs, MainWindow.g.cs for WPF projects, which led to compilation errors such as "no proper Main entry point", "no definition of InitializeComponent", so I had to add the *.g.cs files into the project instance before calling "project.GetCompilationAsync().Result". But when I upgraded to 5.8 preview, it seems like the project instance now can "see" such files, and since I added them manually, it then shows the compilation errors related to the duplicated definition of those components. Does 5.8 change the mechanism of design-time build? Should I remove the implementation of manually adding compiler-generated files from now?

**Comment by jasonmalinowski** [comment]
@awesome-liuxiao Ah if you were using packages.config then it's possible you were getting a mismatch of binaries deployed with your application. That's not something we've really tested or supported for a long time. If it's working now with current bits then I'd say you're good.

We didn't make any changes for the design time build mechanism generally, but I'm wondering if earlier you were still hitting some sort of internal failure and that was causing the design time build to not properly run. Again, maybe you had some mismatched bits, or the AppDomain isolation we added in the new version is benefitting you too. But yes, you should be able to remove any code manually adding generated files; that should be something we handle properly.
