### ISSUE TITLE
error CS8640: Expression tree cannot contain value of ref struct or restricted type 'ReadOnlySpan' to restrictive

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/roslyn#31957]
**Version Used**: 
3.0.100-preview-009844
**Steps to Reproduce**:
In Preview1 and in previous versions the following code snippet produced a valid MethodInfo for the generic static method with a byref struct, since #30776 it does not compile anymore.
```csharp
Expression<Action> functor = () => MemoryMarshal.AsBytes(new ReadOnlySpan<char>());
var asBytesMethodInfo = (functor.Body as MethodCallExpression).Method;
```
**Motivation**:
As many probably know, finding the correct MethodInfo for reflection (or in this case Expression Trees in SpanJson) for extension methods and/or methods with generic arguments is a bit of work, especially if the there are multiple overloads with the same name (LINQ's IEnumerable<T>...)
One of the more generally accepted shortcuts is to use an expression tree to describe the method and obtain the MethodInfo like above. This works nicely with pretty much everything.
Unfortunately in #30776 you now prevent this via the following compilation error:
error CS8640: Expression tree cannot contain value of ref struct or restricted type 'ReadOnlySpan'.

Isn't there maybe a less restrictive bugfix which still allows the above way to work, as the above Expression is never executed or compiled?

**Expected Behavior**:
I get the MethodInfo for ``AsBytes`` for the generic argument ``char``and the parameter ``ReadOnlySpan<char>``.
**Actual Behavior**:
error CS8640: Expression tree cannot contain value of ref struct or restricted type 'ReadOnlySpan'.

**Comment by AArnott** [comment]
This compile error blocks me from building my https://github.com/aarnott/nerdbank.streams repo with VS 2019.

**Comment by LeroyK** [comment]
I am running into this issue as well. This expression compiles in VS2017 15.9.11, but fails to compile in VS 2019 16.1 Preview 2:
```c#
x => x.AsSpan().ToArray()
```
