### ISSUE TITLE
Dictionary with Func with DateTime does not compile (parsing error)

### ISSUE THREAD

**Issue by bradmarder** [dotnet/roslyn#22830]
```
using System;
using System.Collections.Generic;

namespace CompilerBug
{
    class Program
    {
        static void Main(string[] args)
        {
            new Dictionary<int, Func<int, bool>>
            {
                [0] = x => DateTime.UtcNow < DateTime.UtcNow,
                [1] = x => true
            };
        }
    }
}

```

```
C:\source\repos\CompilerBug>dotnet build
Microsoft (R) Build Engine version 15.5.160.37545 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,21): error CS1031: Type expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,1): error CS1031: Type expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,18): error CS1001: Identifier expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,21): error CS1003: Syntax error, '>' expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]

Build FAILED.

Program.cs(13,21): error CS1031: Type expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,1): error CS1031: Type expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,18): error CS1001: Identifier expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
Program.cs(13,21): error CS1003: Syntax error, '>' expected [C:\source\repos\CompilerBug\CompilerBug\CompilerBug.csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.87
```

Doing any of the following will make it compile.
-Changing the `<` sign to `>` 
-Changing the `<` sign to `==`
-Removing the line ` [1] = x => true`
-Adding `&& true` to the expression `DateTime.UtcNow < DateTime.UtcNow`

```
C:\source\repos\CompilerBug>dotnet --info
.NET Command Line Tools (2.1.1-preview-007094)

Product Information:
 Version:            2.1.1-preview-007094
 Commit SHA-1 hash:  f657648f07

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1-preview-007094\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
```

**Comment by svick** [comment]
Based on `git bisect`, this is a regression caused by #22102.

**Comment by jcouv** [comment]
Thanks all (for the report, tracking down the root cause, and proposing a fix).
Tagging @gafter (given this is a regression, it may meet the bar for 15.5).

**Comment by gafter** [comment]
Integrated in https://github.com/dotnet/roslyn/pull/22856

**Comment by jcouv** [comment]
@bradmarder This fix will make it into 15.6.
