### ISSUE TITLE
Move analyzers to GetBestTypeByMetadataName

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43341]
Currently many analyzers in dotnet/roslyn use `Compilation.GetTypeByMetadataName`. This method does not handle multiple definitions of types (even when only one is accessible), which leads to failures such as the one fixed in #43205. The `Compilation.GetTypeByMetadataName` method should be added to the banned APIs, and analyzers updated to use `CompilationExtensions.GetBestTypeByMetadataName` instead.

**Comment by CyrusNajmabadi** [comment]
Closing out.  We should either do this (and then assign a milestone to this), or just accept that our code does not.
