### ISSUE TITLE
Unable to cast nullable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#42867]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/721033/unable-to-cast-nullable.html)._

---
After updating VS to 16.2.* we have some issue debugging a WPF application started directly from VS.

1) It ignores the system NumberFormat/DateFormat and uses normal en-US (if I start the application directly from the bin\Debug it works as expcted) and ignores NumberFormats set in the OS

2) We are unable to cast Decimal?= to Decimal? (only in debug session as described above). this is Immediate window's paste, but its the same problem:
pthis. Value = 1M
error CS0029: Cannot implicitly convert type 'decimal' to 'T?'

pthis. Value = (decimal?) 1M
error CS0029: Cannot implicitly convert type 'decimal?' to 'T?'

typeof(T?). FullName
Internal error in the C# compiler

typeof(T). FullName
"System.Decimal"

pthis. Value = new T? (1M)
Internal error in the C# compiler

---
#### Visual Studio Feedback System on 9/3/2019, 11:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/8/2019, 02:25 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Visual Studio Feedback System on 3/27/2020, 00:39 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by RikkiGibson** [comment]
I'm confused by the `Main()` method in this repro. `new C<T>()` seems invalid since there is no type parameter T in scope.

**Comment by tmat** [comment]
Sorry, that was just typo. Updated.
