### ISSUE TITLE
(Linux only?) Method group intrinsic type ignores params and default arguments

### ISSUE THREAD

**Issue by ClearScriptLib** [dotnet/roslyn#69797]
**Version Used**: 

.NET 7

**Steps to Reproduce**:
``` C#
public class Program {
    public static void Main() {
        var paramsMethod = ParamsMethod;
        paramsMethod("123", "321", "231");
    }
    public static void ParamsMethod(params string[] args) => Array.ForEach(args, Console.WriteLine);
}
```

**Expected Behavior**:

Windows output:
```
D:\Code\Foo>dotnet run
123
321
231
```

**Actual Behavior**:

Linux output:
```
/mnt/d/Code/Foo$ dotnet run
/mnt/d/Code/Foo/Program.cs(4,9): error CS1593: Delegate 'Action<string[]>' does not take 3 arguments [/mnt/d/Code/Foo/Foo.csproj]

The build failed. Fix the build errors and run again.
```

A similar inconsistency occurs with method signatures that include default arguments.

**Comment by jjonescz** [comment]
Works for me with .NET 7.0.306. What's your `dotnet --version` on Linux? And if you add line `#error version` to the beginning of your `Program.cs`, what is the output of `dotnet build` then?

**Comment by ClearScriptLib** [comment]
>What's your `dotnet --version` on Linux?

7.0.102

>And if you add line `#error version` to the beginning of your `Program.cs`, what is the output of `dotnet build` then?

```
/mnt/d/Code/Foo$ dotnet run
/mnt/d/Code/Foo/Program.cs(1,8): error CS1029: #error: 'version' [/mnt/d/Code/Foo/Foo.csproj]
/mnt/d/Code/Foo/Program.cs(1,8): error CS8304: Compiler version: '4.4.0-6.22580.4 (d7a61210)'. Language version: 11.0. [/mnt/d/Code/Foo/Foo.csproj]

The build failed. Fix the build errors and run again.
```

**Comment by ClearScriptLib** [comment]
UPDATE: This appears to be fixed in 7.0.400. It would be helpful to know which version fixed it. Thank you!

**Comment by jjonescz** [comment]
> It would be helpful to know which version fixed it.

Looks like it works since 7.0.200. Doesn't work in 7.0.1xx.
