### PR TITLE
Extensions: definite assignment and region analysis

### PR DESCRIPTION
**Pull request by jcouv**
I chose to keep `TryGetThisParameter`/`MethodThisParameter` returning a proper `this` symbol for instance methods (rather than `null`). But it's disallowed to use it (via `HasThis`).

Relates to test plan https://github.com/dotnet/roslyn/issues/76130

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 1]
```diff
@@ -1832,6 +1852,16 @@ protected override LocalState TopState()
                             }
                         }
                     }
+
+                    if (TryGetInstanceExtensionParameter(out ParameterSymbol extensionParameter))
+                    {
+                        Debug.Assert(thisParameter.RefKind != RefKind.Out);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:1858]: >Debug.Assert(thisParameter.RefKind != RefKind.Out); [](http://example.com/codeflow?start=24&length=51)

Is this true even in an error scenario?

File: src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs [hunk 2]
```diff
@@ -79,23 +79,6 @@ internal static bool GetIsVararg(this Symbol member)
...
-            {
-                case SymbolKind.Method:
-                case SymbolKind.Property:
-                    return member.ContainingSymbol is TypeSymbol { IsExtension: true };
-                default:
-                    throw ExceptionUtilities.UnexpectedValue(member.Kind);
-            }
-        }
-
-        internal static bool GetIsNewExtensionMember(this MethodSymbol member)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MemberSymbolExtensions.cs:93]: >nternal static bool GetIsNewExtensionMember(this MethodSymbol member) [](http://example.com/codeflow?start=9&length=69)

I do not understand why these overloads a re removed. I intentionally added them to avoid the need to check the symbol kind

File: src/Compilers/CSharp/Portable/Symbols/Symbol.cs [hunk 3]
```diff
@@ -1742,6 +1741,11 @@ internal static bool IsCaptured(Symbol variable, SourceMethodSymbol containingSy
                     throw ExceptionUtilities.UnexpectedValue(variable.Kind);
             }
 
+            if (containingSymbol.GetIsNewExtensionMember() && ReferenceEquals(variable.ContainingSymbol, containingSymbol.ContainingSymbol))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Symbol.cs:1744]: >ReferenceEquals(variable.ContainingSymbol, containingSymbol.ContainingSymbol) [](http://example.com/codeflow?start=62&length=77)

Is this an indirect/veiled way to check whether the ```variable``` is an extension parameter? Consider checking for that explicitly instead.

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 4]
```diff
@@ -24753,4 +24752,419 @@ public static void M<U>(U u) { }
...
+        {
+            o.M2();
+        }
+        public void M2() { }
+    }
+}
+""";
+        var comp = CreateCompilation(src);
+        comp.VerifyEmitDiagnostics(
+            // (7,13): error CS0103: The name 'o' does not exist in the current context
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:24940]: >// (7,13): error CS0103: The name 'o' does not exist in the current context [](http://example.com/codeflow?start=12&length=75)

This test is going to cause a conflict with #77704

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 5]
```diff
@@ -24753,4 +24752,419 @@ public static void M<U>(U u) { }
...
+        public void RegionAnalysis_01()
+        {
+            var analysisResults = CompileAndAnalyzeDataFlowExpression("""
+static class E
+{
+    extension(int i)
+    {
+        public void M(int i2)
+        {
+            _ = /*<bind>*/i + i2/*</bind>*/;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:25035]: >i [](http://example.com/codeflow?start=26&length=1)

Consider adding a flavor of the test where ```i``` is assigned within the region

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:24940]: Yup. I'll merge/resolve after your PR goes in

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 6]
```diff
@@ -24753,4 +24752,593 @@ public static void M<U>(U u) { }
...
+CapturedInside: i, i2
+CapturedOutside:
+DataFlowsIn:
+DataFlowsOut: i, i2, i3
+DefinitelyAssignedOnEntry: this
+DefinitelyAssignedOnExit: i, this, i2, i3
+ReadInside:
+ReadOutside: i, i2, i3
+WrittenInside: i, i2, i3
+WrittenOutside: this
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:25318]: >this [](http://example.com/codeflow?start=16&length=4)

The fact that `this` is mentioned in the result (in any symbol set) feels somewhat unexpected.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:25318]: Consider at least adding a prototype comment

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3)

**Comment by jcouv** [comment]
@jjonescz for review. Thanks

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 7]
```diff
@@ -1832,6 +1852,18 @@ protected override LocalState TopState()
                             }
                         }
                     }
+
+                    if (TryGetInstanceExtensionParameter(out ParameterSymbol extensionParameter))
+                    {
+                        if (extensionParameter.RefKind != RefKind.Out)
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:1858]: Consider collapsing these `if` conditions into one.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 8]
```diff
@@ -368,6 +368,11 @@ protected override ImmutableArray<PendingBranch> Scan(ref bool badRegion)
                 }
             }
 
+            if (TryGetInstanceExtensionParameter(out ParameterSymbol extensionParameter))
+            {
+                EnterParameter(extensionParameter);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:373]: Should we also `LeaveParameter(extensionParameter);` below like we do for `methodThisParameter`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs [hunk 9]
```diff
@@ -87,6 +87,11 @@ protected override void EnterRegion()
                         if (p.RefKind != RefKind.None) _readOutside.Add(p);
                     }
 
+                    if (TryGetInstanceExtensionParameter(out ParameterSymbol extensionParameter))
+                    {
+                        if (extensionParameter.RefKind != RefKind.None) _readOutside.Add(extensionParameter);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs:92]: Consider collapsing the `if` conditions into one.

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 10]
```diff
@@ -15466,12 +15469,8 @@ static class E
     public static ref string M(this ref string s) => ref s;
 }
 """;
-        // PROTOTYPE unexpected definite assignment error and missing error on extension parameter
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:15469]: > missing error on extension parameter

Looks like this part of the prototype comment wasn't addressed.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs (hunk 7 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:1858]: I'll leave this as-is to match surrounding code

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 11]
```diff
@@ -2640,21 +2640,27 @@ public void ReceiverParameter_Out_01()
...
 }
 """;
         var comp = CreateCompilation(src);
         comp.VerifyEmitDiagnostics(
             // (3,15): error CS8328:  The parameter modifier 'out' cannot be used with 'extension'
-            //     extension(out int i) { }
+            //     extension(out int i)
             Diagnostic(ErrorCode.ERR_BadParameterModifiers, "out").WithArguments("out", "extension").WithLocation(3, 15),
-            // (4,17): error CS0177: The out parameter 'i' must be assigned to before control leaves the current method
+            // (5,14): error CS0177: The out parameter 'i' must be assigned to before control leaves the current method
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:2655]: >// (5,14): error CS0177: The out parameter 'i' must be assigned to before control leaves the current metho [](http://example.com/codeflow?start=12&length=106)

Is this error going to be reported for a static method?

Comment (jcouv) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:2655]: It should not. We only enter/leave the extension parameter for instance methods. I'll add a test

**Review by jjonescz — APPROVED** [review]
