### ISSUE TITLE
Using SourceGenerators leads to CS0016 when path is too long

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [dotnet/roslyn#62544]
**Version Used**: 4.2.0-4.22281.5 (8d3180e5)
Also observed on some previous 4.2.* versions
I'm not sure when I updated to 4.1.*
I think it was working on 4.0.*

**Steps to Reproduce**:

1. Clone https://github.com/SonarSource/sonar-dotnet into path that is at least 45 character long. For example 
 ```
C:\Projects\.Community\Xxxxxxx sonar-dotnet
 ```
3. Open `analyzers\SonarAnalyzer.sln`
4. Try to build it

**Expected Behavior**:

Project should build. Just as it builds on shorter path like 
```
C:\Projects\sonar-dotnet
```

**Actual Behavior**:

Build fails.
Our project uses Source Generators from StyleCop that generates dozens of files. These 7 files have path longer than 256 characters and fails to be generated. 

```
3>------ Build started: Project: SonarAnalyzer.CFG, Configuration: Debug Any CPU ------
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\net46\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionListSyntaxWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\net46\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionListSyntaxWrapper.g.cs'.'
3>Done building project "SonarAnalyzer.CFG.csproj" -- FAILED.
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\IObjectOrCollectionInitializerOperationWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\IObjectOrCollectionInitializerOperationWrapper.g.cs'.'
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\ICollectionElementInitializerOperationWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\ICollectionElementInitializerOperationWrapper.g.cs'.'
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\IStaticLocalInitializationSemaphoreOperationWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.OperationLightupGenerator\IStaticLocalInitializationSemaphoreOperationWrapper.g.cs'.'
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionListSyntaxWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionListSyntaxWrapper.g.cs'.'
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionSyntaxWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\FunctionPointerUnmanagedCallingConventionSyntaxWrapper.g.cs'.'
3>CSC : error CS0016: Could not write to output file 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\ImplicitStackAllocArrayCreationExpressionSyntaxWrapper.g.cs' -- 'Could not find a part of the path 'D:\Projects\.Community\Xxxxxxx sonar-dotnet\analyzers\src\SonarAnalyzer.CFG\obj\Debug\netstandard2.0\generated\SonarAnalyzer.ShimLayer.CodeGeneration\StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator\ImplicitStackAllocArrayCreationExpressionSyntaxWrapper.g.cs'.'
3>Done building project "SonarAnalyzer.CFG.csproj" -- FAILED.
```

**Note**:
I'm sure this was working fine before on the same path. Last time I worked with this path was around 01/2022

**Comment by pavel-mikula-sonarsource** [comment]
We've realized that this issue started to demonstrate itself some time after we added 
```
<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
```
That explains why it was working some time ago. So the problem with long paths existed probably since the very beginning and it is not a regression.

**Comment by tmat** [comment]
@[pavel-mikula-sonarsource](https://github.com/pavel-mikula-sonarsource) Do you have any issues with enabling long paths on your machine?

**Comment by pavel-mikula-sonarsource** [comment]
What are the changes that I need to do to enable those for Roslyn?

**Comment by tmat** [comment]
Running the following from elevated command prompt should enable long paths for the system:
```
reg ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1
```

**Comment by pavel-mikula-sonarsource** [comment]
I confirmed that the registry hack solved the problem.

Díky

**Comment by PeterHevesi** [comment]
Or what if Long Paths are always enabled in all windows?
