### ISSUE TITLE
CS0103 error on SDK 6.0.416

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn#70713]
**Version Used**: Compiler version: '4.3.1-3.22526.13 (41a5af9d)'. Language version: 10.0. SDK version: 6.0.416

**Steps to Reproduce**:

Create a simple `classlib` project targeting `net6.0` with this class:

```csharp
using System.Runtime.CompilerServices;

namespace CS0103;

public class C
{
    private static void M(int argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null) {}
}
```

**Diagnostic Id**: CS0103

**Expected Behavior**: the code compiles

**Actual Behavior**: error CS0103: The name 'argument' does not exist in the current context

**Note**: The code compiles with fine with Compiler version: '4.7.0-3.23465.3 (b5c9211b)'. Language version: 10.0. SDK version 7.0.403.

**Comment by paulomorgado** [comment]
OOPS! That's a C# 11.0 feature: [Extended `nameof` scope](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#extended-nameof-scope)
