### ISSUE TITLE
error CS0121: "The call is ambiguous between the following methods or properties" after upgrade from net5.0 to 6.0.0-rc.1.21451.3

### ISSUE THREAD

**Issue by christothes** [dotnet/roslyn#57101]
### Description

For code that compiled with no errors on .net5, the following errors appeared after upgrading to 6.0.0-rc.1.21451.3:

`error CS0121: The call is ambiguous between the following methods or properties: 'Assert.That<TActual>(ActualValueDelegate<TActual>, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)' `

### Reproduction Steps

Attempt to compile the following NUnit assertion

```c#
Assert.That(() => Foo.Bar(), Throws.InstanceOf<ArgumentNullException>());

public class Foo
{
	public void Bar()
	{
		throw new ArgumentNullException();
	}
}
```

### Expected behavior

Code compiles without error

### Actual behavior

error CS0121: The call is ambiguous between the following methods or properties: 'Assert.That<TActual>(ActualValueDelegate<TActual>, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)' 

### Regression?

Does not reproduce with .net 5.0.10

### Configuration

6.0.0-rc.1.21451.3
Windows 11 x64
