### ISSUE TITLE
Changed build behavior of object initialization of init-only properties

### ISSUE THREAD

**Issue by EchoDelta** [dotnet/roslyn#51944]
Given this simple .NET 5.0 console app (`Program.cs`):

```c#
var foo = new Foo
{
    Bar = {
        Baz = "baz"
    }
};

class Foo
{
    public Bar Bar { get; } = new();
}

class Bar
{
    public string Baz { get; init; }
}
```

We experience that this builds with version 5.0.102 of the SDK, but fails with SDK version 5.0.201 with the following error:

```
error CS8852: Init-only property or indexer 'Bar.Baz' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.
```

We can toggle between versions in `global.json` and the difference in build behavior seem consistent.

How is "nested" object initializing and init-only properties intended to work in this case? Should this build or not?

From `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295
```

**Comment by jaredpar** [comment]
Thanks for taking the time to report this behavior unfortunately it is "By Design". The feature in use here is nested initilaizers which are slightly different than object initializers in that they are mutating existing values vs. creating new ones. This violates the contract of `init` accessors and hence it's an error to use them in this way. This was discovered in the 5.0.100 SDK and fixed in 5.0.200 SDK. 

The original tracking issue is #50126
