### ISSUE TITLE
Ref safety errors reported for deconstruction assignment with discard

### ISSUE THREAD

**Issue by cston** [dotnet/roslyn#65522]
Compile with VS 17.4.0 / csc 4.4.0-3.22518.13 (7856a68c):
```csharp
using System;
class Program
{
    static void F1()
    {
        Span<int> s1 = stackalloc int[10];
        s1.Deconstruct(out s1, out _); // ok
    }
    static void F2()
    {
        Span<int> s2 = stackalloc int[10];
        (s2, _) = s2; // errors
    }
}
static class Extensions
{
    public static void Deconstruct(this Span<int> self, out Span<int> x, out Span<int> y)
    {
        throw null;
    }
}
```

**Expected Behavior**:
No errors

**Actual Behavior**:
(12,9): error CS8352: Cannot use variable '(s2, _) = s2' in this context because it may expose referenced variables outside of their declaration scope
(12,19): error CS8350: This combination of arguments to 'Extensions.Deconstruct(Span<int>, out Span<int>, out Span<int>)' is disallowed because it may expose variables referenced by parameter 'self' outside of their declaration scope

**Comment by jaredpar** [comment]
@RikkiGibson on the surface looks pretty similar to #64784
