### PR TITLE
A switch expression only has a common type if all arms can be converted to that type.

### LINKED ISSUE #38226: Compiler computes incorrect common type for switch expression with null arm
See https://github.com/dotnet/roslyn/issues/37950

The following method does not compile, but it should.  A switch expression should only be considered to have a natural type when all switch arm expressions can be converted to the computed common type.

``` c#
class Program
{
    public static void Main() { }

    public static bool? GetBool(string name)
    {
        return name switch
        {
            "a" => true,
            "b" => false,
            _ => null, // error CS0037: Cannot convert null to 'bool' because it is a non-nullable value type
        };
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #38226

### CODE REVIEW

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md [hunk 1]
```diff
@@ -8,3 +8,6 @@ Each entry should include a short description of the break, followed by either a
     bool M<T>(T t) => t is null;
     ```
 However, in *Visual Studio 2019* we improperly permitted this to compile in language versions `7.0`, `7.1`, `7.2`, and `7.3`.  In *Visual Studio 2019 Update 1* we will make it an error (as it was in *Visual Studio 2017*), and suggest updating to `preview` or `8.0`.
+
+2. https://github.com/dotnet/roslyn/issues/38226 When there exists a common type among those arms of a switch expression that have a type, but there are some arms that have an expression without a type (e.g. `null`) that cannot convert to that common type, the compiler improperly inferred that common type as the natural type of the switch expression. That would cause an error.  In VS 2019 Update 4, we fixed the compiler to no longer consider such a switch expression to have a common type.  This may permit some programs to compile without error that would produce an error in the previous version.
```
Comment (jasonmalinowski) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: If you build an app built with the 3.0 SDK in 16.4, which compiler is used during build time? One that will have this fix or one that won't? My worry is if the langver isn't changing, does the IDE know which rules to apply when determining if casts can be removed?

File: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs [hunk 2]
```diff
@@ -131,10 +132,24 @@ private TypeSymbol InferResultType(ImmutableArray<BoundSwitchExpressionArm> swit
...
             }
 
+            seenTypes.Free();
             HashSet<DiagnosticInfo> useSiteDiagnostics = null;
             var commonType = BestTypeInferrer.GetBestType(typesInOrder, Conversions, ref useSiteDiagnostics);
+            typesInOrder.Free();
+
+            if (commonType is object)
+            {
+                foreach (var @case in switchCases)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs]: Perhaps a note as to why this is necessary. It makes sense the context of this PR, but would be surprising just reading the code I think.

File: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs [hunk 3]
```diff
@@ -116,7 +116,8 @@ ImmutableArray<BoundDecisionDagNode> nonNullSuccessors(BoundDecisionDagNode n)
         }
 
         /// <summary>
-        /// Infer the result type of the switch expression by looking for a common type.
+        /// Infer the result type of the switch expression by looking for a common type
+        /// to which every arm's expression can be converted.
         /// </summary>
         private TypeSymbol InferResultType(ImmutableArray<BoundSwitchExpressionArm> switchCases, DiagnosticBag diagnostics)
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs]: We do, several lines down where the variable `commonType` is declared.

---
In reply to: [318338359](https://github.com/dotnet/roslyn/pull/38232#discussion_r318338359) [](ancestors = 318338359)

[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs]: That method takes an immutable array of expressions and computes an array builder of types to pass to `BestTypeInferred`.  But we don't have an immutable array of expressions here.

---
In reply to: [318338359](https://github.com/dotnet/roslyn/pull/38232#discussion_r318338359) [](ancestors = 318338359)
