### ISSUE TITLE
Ternary with a byte variable and direct integer value assignation seems not working anymore since 5.0.2

### ISSUE THREAD

**Issue by BlowaXD** [dotnet/roslyn#51597]
**Version Used**: 5.0.200

**Steps to Reproduce**:

1. Write a ternary with a byte value
byte Ternary with an explicit integer value produces an error, it seems like it interprets the integer value as an int instead of byte

**Expected Behavior**:
Compiling normally

**Actual Behavior**:
Giving an error

This piece of code is not compiling anymore and produces the following error:
```
Program.cs(11,26): error CS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
```
```cs
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var rand = new Random();
            byte otherValue = 0;
            byte test1 = rand.Next(2) > 1 ? 1 : otherValue;
            Console.WriteLine("Hello World!");
        }
    }
}
```

Is it a new intended behavior? I thought byte could be inferred by the compiler like in previous version

**Comment by RikkiGibson** [comment]
This could be a bug in the target-typed conditional expression feature. #43186

**Comment by BlowaXD** [comment]
Hello, it looks like it compiles without any problem on 5.0.103

**Comment by rhaokiel** [comment]
I can confirm the ternary operator worked with `int` literals stored in `byte` variable up until the update pushed yesterday.

Works on Roslyn:  3.8.0-5.20562.2
Does not work on Roslyn: 3.9.0-6.21124.20

.NET version does not seem to affect this issue. Both test cases running 5.0.3

**Comment by Youssef1313** [comment]
@RikkiGibson Based on https://github.com/dotnet/roslyn/issues/51450#issuecomment-785315705, I think this is expected.

**Comment by jaredpar** [comment]
This was an intentional change. That type of conversion was accidentally allowed in 16.8 and was fixed in 16.9. Primary issue is #49598
