### ISSUE TITLE
MSBuildWorkspace does not cleanly load blazorwasm project

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn#72015]
**Version Used**: 4.10 Preview 1

Reported in https://github.com/dotnet/roslyn/pull/69225

**Steps to Reproduce**:

1. dotnet new blazorwasm (or blazor or blazorwasm-empty)
2. use MSBuildWorkspace.OpenProjectAsync to load the newly created project

**Expected Behavior**:
Project loads without any workspace diagnostics and compilation reports no compiler diagnostics.

**Actual Behavior**:
Compilation reports "CS0246: The type or namespace name {'csharp_blazor_project'|'App'} could not be found (are you missing a using directive or an assembly reference?)"

**Possibly unrelated**
I noticed that the C# extension in VS Code reports the following when opening the blazorwasm project.
```
Generator 'RazorSourceGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'TypeLoadException' with message 'Type 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1[TInput]' from assembly 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is attempting to implement an inaccessible interface.'.
System.TypeLoadException: Type 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1[TInput]' from assembly 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is attempting to implement an inaccessible interface.
   at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.GeneratorExtensions.RegisterHostOutput[TSource](IncrementalGeneratorInitializationContext& this, IncrementalValuesProvider`1 source, Action`3 action)
   at Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator.Initialize(IncrementalGeneratorInitializationContext context)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/GeneratorDriver.cs:line 226
```

**Comment by jasonmalinowski** [comment]
@jaredpar @chsienki @jjonescz I'm wondering if this was broken by https://github.com/dotnet/roslyn/pull/71579. The generator being loaded from the SDK is one that still expects the ExternalAccess to be there, but we don't have it any more for newer Roslyn builds.

This seems like fallout for how the razor generator is expected to load:

- in a dotnet build, the SDK bits are all matched. 
- in VS for Windows, we're loading the generator that ships in the IDE so it's matched with the compiler bits there
- for VS Code we're discussing doing the same thing, but we're not doing that yet, which might explain the error @JoeRobich saw
- for MSBuildWorkspace we'll do...what? We're not shipping a Razor generator to load from anywhere that may match the Roslyn version the user's app is.

**Comment by jjonescz** [comment]
If I read the error message correctly, the ExternalAccess.RazorCompiler dll is present, it just cannot implement internal CodeAnalysis interface anymore. I think we could just keep the IVTs around to solve this (https://github.com/dotnet/roslyn/pull/71579#discussion_r1448976647).

**Comment by jasonmalinowski** [comment]
@jjonescz Does that mean at this point the expectation is the core compiler binaries are always maintaining the APIs that the old ExternalAccess was accessing?

**Comment by jjonescz** [comment]
> Does that mean at this point the expectation is the core compiler binaries are always maintaining the APIs that the old ExternalAccess was accessing?

Hm, good question. It should be enough if we keep them as stubs (if we want to remove or rename them in the future) - because the razor compiler never actually uses them (the machinery was supposed to be used by razor IDE to get design-time outputs out of the razor compiler).

**Comment by jonashendrickx** [comment]
If it is fixed, when can we expect a backport to 8.0.2?

**Comment by jonashendrickx** [comment]
When can we expect the fix to be released?

**Comment by jonashendrickx** [comment]
> > When can we expect the fix to be released?
> 
> Visual Studio 17.10 Preview 3 (and .NET SDK 8.0.300 I think). In about a month.

Doesn't it affect also Visual Studio / MSBuild 17.9? My Blazor project has been broken since 17.9 when running `dotnet format`.

**Comment by jjonescz** [comment]
> Doesn't it affect also Visual Studio / MSBuild 17.9?

I don't think that's possible, the issue described here was introduced in VS 17.10 Preview 1 by https://github.com/dotnet/roslyn/pull/71579 which didn't get into VS 17.9 nor SDK 8.0.200.

> Can you backport the fix 17.9?

The IVT has never been removed from the 17.9 branch, so there's nothing to fix there:

https://github.com/dotnet/roslyn/blob/989117396f26e5453ff157df610d22ce45b6b0a9/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj#L83

**Comment by jasonmalinowski** [comment]
@jonashendrickx Can you share the error you're getting just to make sure we're discussing the same bug?

**Comment by jjonescz** [comment]
@jasonmalinowski see https://github.com/dotnet/format/issues/2119

**Comment by jonashendrickx** [comment]
@jasonmalinowski https://github.com/bitwarden/passwordless-server/actions/runs/7989471492/job/21816103177

It's here saying the directives are unused and cannot be removed, but they are in fact being used.
