### ISSUE TITLE
The call is ambiguous for an extension menthod with overload 'this ref T' despite valid constraints for T

### ISSUE THREAD

**Issue by ghost** [dotnet/roslyn#26197]
posted by @Makeman-from-Makeloft

**Version Used**:  https://sharplab.io/

**Steps to Reproduce**:
Try to compile [this code](https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgNQMwMQNgQCY4BhOAbwzhoVyUIBU5GB7AHkYD4AKAFwAWASwDOcAE4BTAGYs4rAJRwA7gMlSWIOCL7iArgGM+cALxd5adLTp4mLDt37CxzRSrUbGWqCTMXqtAE0APQAVHAAdkIGknB8rHACAIYAbrGhwUFwwcE4tnJsnLyCohIycm5+rJbWYfLicBlZOXkMBQ7FznBCERVKVTWBVrStBAgALHgAHDxKVMPWND3GQqZwMIOLeACcPGw8UrJCCgqbi0i7+xGSynAA8gBGAFaSRrMnZ9ZZ1hc8QgB0+w+2WCcHU4lYDVIAGUYIgiIgtIw1HADEkADbo7piJIAWweQgA5npWHoRN8Rohdtdbo8Xm8FIDWO9kCCweIIVDYfDESwUWjMdi4HiCcTSeSFnAAL4YKVAA==)  

```c#
using System;

public static class C {
    public static T To<T>(this ref T o) where T: struct => o;
    public static T To<T>(this T o) where T: class => o;
    
    /* nice to have */
    //public static T To<T>(this ref T o) => o;
    /* or */
    //public static T To<T>(this in T o) => o;
    
    public static void Main() {
        int i = 0;
        Console.WriteLine(To(ref i));
        Console.WriteLine(To(new Object()));
        
        Console.WriteLine(i.To()); // error CS0121: The call is ambiguous
        Console.WriteLine(new Object().To()); // error CS0121: The call is ambiguous
    }
}
```

**Actual Behavior**:
Compilation errors ('The call is ambiguous')

**Expected Behavior**:
Call according constraints
```c#
where T: struct
where T: class
```

**Nice to Have**:
A single unconstarained method without overloads like
```c#
public static T To<T>(this ref T o) => o;
/* or */
public static T To<T>(this in T o) => o;
```

**Comment by Neme12** [comment]
This actually works in C# 7.3 as part of https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/improved-overload-candidates.md

**Comment by Neme12** [comment]
See https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsBmQogNkICZ8BhfAb0v18LuJMAKviEB7ADxCAfAAoYACwCWUfAjgAzUfjEBKfAHcFiOKJD5YCAK4BjGPgC80neQp9+9YaMkz5y1SJ6hsbqZiyOzmKu7jx8APQAVPgAdko2pjBi+AoQAG6mCXGxvHFxtJ7a4lJyiipqmtpBTi7F+Ik6CPiFraXlgpU+Nf74SsmN+s1Rra19jIQALPQAHLL63G7ufKP2So74uNGbvMQAnLLisupaSrq6h0en52KyyXAG+ADywABWcHart3um1a7keSgAdBdAW04vhEAgxJ02ABlXBEZhEcxCYz4GwQAA2+JGqggYGASgA5lYxFYoCC+I9Xu8vr9/rpIc9oaU4QgEUjUejMaIcXjCcT8KTyVSaXSNrwAL6UeVAA=

**Comment by mkmn-xyz** [comment]
posted by @Makeman-from-Makeloft

Nice, thank!

What about the proposal to have a single unconstarained method without overloads like
```c#
//public static T To<T>(this ref T o) => o;
/* or */
public static T To<T>(this in T o) => o;
```
to avoid duplication of implementation?

As I understand
```c#
public static T To<T>(this ref T o) => o;
```
is being disallowed to avoid reassignment of `o`, isn't it?

Seems that
```c#
public static T To<T>(this in T o) => o;
```
has not this lack.

Or do I misunderstand something?

**Comment by mkmn-xyz** [comment]
@gafter 
Nice news, github allowed to remove ghost's comments! What about ghost's issues?

Maybe it will be more constructive if you answer on my question about `in` extension method or create a related proposal, will not it?

```c#
public static T To<T>(this in T o) => o;
```

> 
> 
> posted by @Makeman-from-Makeloft
> 
> Nice, thank!
> 
> What about the proposal to have a single unconstarained method without overloads like
> 
> //public static T To<T>(this ref T o) => o;
> /* or */
> public static T To<T>(this in T o) => o;
> 
> to avoid duplication of implementation?
> 
> As I understand
> 
> public static T To<T>(this ref T o) => o;
> 
> is being disallowed to avoid reassignment of o, isn't it?
> 
> Seems that
> 
> public static T To<T>(this in T o) => o;
> 
> has not this lack.
> 
> Or do I misunderstand something?
