### ISSUE TITLE
Microsoft.CodeAnalysis 1.0.0 cannot be used in VS2012

### ISSUE THREAD

**Issue by poizan42** [dotnet/roslyn#4166]
msbuild v4 seems to get confused by referencing a newer version of the build tools. The full output from building a project referencing Roslyn 1.0.0 when built with msbuild 4.6.57.0 on a system with build tools 2015 RC installed:

	Microsoft (R) Build Engine version 4.6.57.0
	[Microsoft .NET Framework, version 4.0.30319.0]
	Copyright (C) Microsoft Corporation. All rights reserved.

	Build started 28-07-2015 14:12:42.
	Project "C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj" on node 1 (default targets).
	C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build.Engine, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	GenerateTargetFrameworkMonikerAttribute:
	Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
	CoreCompile:
	  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.CodeAnalysis.CSharp.1.0.0\lib\net45\Microsoft.CodeAnalysis.CSharp.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.CodeAnalysis.CSharp.Workspaces.1.0.0\lib\net45\Microsoft.CodeAnalysis.CSharp.Workspaces.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.CodeAnalysis.Common.1.0.0\lib\net45\Microsoft.CodeAnalysis.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.CodeAnalysis.Workspaces.Common.1.0.0\lib\net45\Microsoft.CodeAnalysis.Workspaces.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\System.Collections.Immutable.1.1.36\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.AttributedModel.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.Convention.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.Hosting.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.Runtime.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\Microsoft.Composition.1.0.27\lib\portable-net45+win8+wp8+wpa81\System.Composition.TypedParts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\packages\System.Reflection.Metadata.1.0.21\lib\portable-net45+win8\System.Reflection.Metadata.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collections.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Collections.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.Annotations.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Debug.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Dynamic.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Globalization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.IO.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Expressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.NetworkInformation.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ObjectModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Reflection.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Resources.ResourceManager.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.InteropServices.WindowsRuntime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Numerics.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Security.Principal.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Duplex.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.NetTcp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.ServiceModel.Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.Encoding.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Text.RegularExpressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Tasks.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Tasks.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Threading.Timer.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.XDocument.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades\System.Xml.XmlSerializer.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ExceptionSerializationCtorFixer.exe /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Users\kb\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs"
	Program.cs(17,30): error CS0234: The type or namespace name 'MSBuild' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	Done Building Project "C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj" (default targets) -- FAILED.

	Build FAILED.

	"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj" (default target) (1) ->
	(ResolveAssemblyReferences target) -> 
	  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]
	  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3258: The primary reference "Microsoft.CodeAnalysis.Workspaces.Desktop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the .NET Framework assembly "Microsoft.Build.Engine, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which has a higher version "14.0.0.0" than the version "4.0.0.0" in the current target framework. [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]

	"C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj" (default target) (1) ->
	(CoreCompile target) -> 
	  Program.cs(17,30): error CS0234: The type or namespace name 'MSBuild' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [C:\Users\kb\Documents\Visual Studio 2012\Projects\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer\ExceptionSerializationCtorFixer.csproj]

		3 Warning(s)
		1 Error(s)

	Time Elapsed 00:00:00.56

The target framework in question here is 4.5.2, but targetting 4.5 and 4.5.1 gives the same result. The result of the warnings is apparently that msbuild just ignores the reference to Microsoft.CodeAnalysis.Workspace.Desktop, resulting in the build failing.

Building it with msbuild v14 works fine. So I tried to force Visual Studio to use the new build tools by adding binding redirects for Microsoft.Build and Microsoft.Build.Framework since they are supposed to be backwards compatible. This approach works fine for a C# project, however loading a F# project failed - the separation between the build tools and Visual Studio seems not to have been as good as one might have hoped for...:

	(TransitionMU)
	0080CAD0 16345777 UNKNOWN!Microsoft.VisualStudio.FSharp.ProjectSystem.ProjectFactory.UpgradeProject_CheckOnly(System.String, Microsoft.VisualStudio.Shell.Interop.IVsUpgradeLogger, Int32 ByRef, System.Guid ByRef, UInt32 ByRef)+0xb7
	0080CAF4 1634564E UNKNOWN!DomainNeutralILStubClass.IL_STUB_COMtoCLR(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)+0x56
	(TransitionUM)
	(TransitionMU)
	0080D8F4 00978418 UNKNOWN!DomainNeutralILStubClass.IL_STUB_CLRtoCOM(UInt32, System.String)+0x98
	(TransitionUM)
	(TransitionMU)
	0080D95C 00977E56 Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.PlatformUI.ProjectMruItem.OnOpen()+0x106
	0080D9C4 00977D29 Microsoft_VisualStudio_Shell_UI_Internal_ni!Microsoft.VisualStudio.PlatformUI.MruItem.OpenCommandHandler(Microsoft.VisualStudio.Shell.Interop.IVsUIDispatch, System.String, System.Object, System.Object ByRef)+0x29

...

	EXCEPTION_OBJECT: !pe 1b40a3f4
	Exception object: 1b40a3f4
	Exception type:   System.TypeLoadException
	Message:          Could not load type 'Microsoft.Build.Construction.SolutionParser' from assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
	InnerException:   <none>
	StackTrace (generated):
	<none>
	StackTraceString: <none>
	HResult: 80131522

I'm not sure what can be done to solve this (besides upgrading Visual Studio, which unfortunately isn't an option right now). Is it possibly that it could be worked around by adding some custom build rules to the NuGet package? Otherwise is it possible that the targeting patches could be updated so msbuild 4 doesn't think the built tools are part of the frameworks? Or VS2012 be updated to be able to use a newer msbuild version? (given that service pack support seems to have ended I'm guessing the latter isn't an option)

**Comment by davkean** [comment]
Consuming Roslyn inside Visual Studio 2012/2013 isn't supported. We depend on MSBuild 14, which those versions of Visual Studio cannot be upgraded to use. If you want to host/use Roslyn in versions prior to VS2015, you should be hosting it in a process that runs outside of MSBuild/VS and have the task communicate with it via remoting, named pipes, WCF or something similar.
