### ISSUE TITLE
Visual Basic line commit hangs the editor while typing

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#48590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804596/running-low-priority-background-processes-stops-me.html)._

---
On a particular project, every time I start it up I have to sit and wait for "Running low priority background processes" to finish. There's no count on how many processes it is working through, and if I try and edit a codebehind page I just get a dialogue box saying "Waiting for an editor command to finish" or similar. It can take hours for it to finish. 

It's OK to do these background processes if they are indeed background processes, but at the moment they seem to be far from "low priority", as I cannot do anything while they are being processed.

I have tried the usual - deleting all temp files and project cache - but it is the same. It has only started happening since I upgraded to VS2019.

---
#### Feedback Bot on 11/4/2019, 01:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dan Warren on 11/4/2019, 06:26 AM: 

<p>I can confirm. I've been having this issue for months, and it's extremely aggravating, when working through Typescript projects. Intellisense is useless, during this process, and it never seems to complete. Restarting visual studio seems to fix it, most of the time, but it will return, within an hour or so. Usually when I'm updating multiple TS files, before it has completed processing the previous TS file change.</p>

#### Craig Cronin on 11/5/2019, 06:32 AM: 

<p>I'm also having the same issue which is also stopping intellisense from working?</p>

#### tung on 11/9/2019, 11:59 AM: 

<p>Also facing this issue with VS2019. VS does not allows me to type normally when this process in running. It is so annoying.</p>

#### Nicholas Sargente on 11/12/2019, 01:24 PM: 

Same issue since updating to 16.3<br><br><br>94 Background tasks trying to load, never complete (even after letting run for days). I&#39;ve tried disabling all plugins, and even running as administrator -- nothing helps<br><br><br>Intellisense has stopped working completely, and doesn&#39;t even syntax highlight the name of my classes in the editor<br><br><br>I can&#39;t even open Windows forms without the app crashing.<br><br><br>Occasionally as I&#39;m typing I&#39;ll even get a popup that tells me to wait while the input is processed.<br><br><br>During compilation errors don&#39;t show up outside the output window eithier (Error list will show 0 errors, and the file in question will not have errors/warnings displayed inline)<br>
#### Feedback Bot on 11/12/2019, 02:43 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Sam Harwell [MSFT] on 11/12/2019, 02:45 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/56900/2ce68afa-ec49-6291-82dd-7e5cf32f39a9.html" nodeid="56900">@Dan Warren</a> <a rel="user" href="https://developercommunity.visualstudio.com/users/206672/9735d0c2-f6a0-6a9b-a3cd-2792ee69b1db.html" nodeid="206672">@Craig Cronin</a> <a rel="user" href="https://developercommunity.visualstudio.com/users/197543/c5dcd8ad-5527-416c-9591-8f44a7eb048e.html" nodeid="197543">@tung</a> <a rel="user" href="https://developercommunity.visualstudio.com/users/208739/e0c26d95-bce0-6d0c-abe9-8d37802e00ac.html" nodeid="208739">@Nicholas Sargente</a> The issue filed by the original poster was narrowed down to a specific issue in a Visual Basic editor feature, which is unrelated to the "Low priority background processes" feature. If you continue to experience issues, please consider filing new feedback items according to the steps at https://aka.ms/reportPerf so we can investigate them individually.</p><p>Thank you,<br>Sam Harwell</p>

#### Feedback Bot on 11/12/2019, 02:49 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Ben Jervis on 11/12/2019, 02:52 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/13574/dcf4b92c-eeb4-6431-9549-12ecbe90be90.html" nodeid="13574">@Sam Harwell [MSFT]</a> Just to be clear, I have multiple projects, and the only one running "low priority background processes" is the one when I have these problems. Once the "low priority background processes" have completed (which these days doesn't tend to happen) Visual Studio then starts to work as normal and I do not receive the commit hanging issue.  </p><p>I trust your judgement of course, but through my experience here I'm not at all convinced it is "unrelated to the 'Low priority background processes' feature". I'll look forward to the fix. </p><p><br></p>

#### Sam Harwell [MSFT] on 11/12/2019, 03:43 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/206191/d928dd3d-ee73-6ba3-84f2-57f62f0c2569.html" nodeid="206191">@Ben Jervis</a> I know this is a bit weird, and we're working on ways to quickly investigate and fix issues related to slow background processing. As for the specific scenario you encountered, even though the editor operations are not directly tied to the background processing, it's certainly possible that these two operations are getting delayed by the same underlying cause. In other words, the background processes message and the slow editing are two different symptoms of the same problem, even though neither is the direct cause of the other.</p>

#### Ben Jervis on 11/12/2019, 03:50 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/13574/dcf4b92c-eeb4-6431-9549-12ecbe90be90.html" nodeid="13574">@Sam Harwell [MSFT]</a> Thanks for the explanation, that makes perfect sense. Thank you for your support!</p>

#### Ben Jervis on 11/13/2019, 03:30 AM: 

(private comment, text removed)
#### Nicholas Sargente on 11/13/2019, 06:25 AM: 

<p>This also seems to be related to a single project of mine in my solution -- If I unload it the rest of the projects in the solution load correctly. Hopefully that information can help somewhat</p>

#### Hadi Eskandari on 11/20/2019, 04:40 PM: 

<p>Any updates? this is such a pain. VS is almost unusable, every keystroke takes a second or two (as I'm running in a VM).</p>

#### Nicholas Sargente on 11/21/2019, 07:45 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/206627/65d9d15f-8709-403b-a7db-9cb9d44e4bf4.html" nodeid="206627">@Hadi Eskandari</a> I was able to fix it by deleting the build folders for the project in my solution that I isolated the issue down to (The bin and obj directories).<br>After rebuilding the project it seems to be fixed as if there was a bad object file or something. It's only popped up twice in the past week and both times I was able to fix it by doing the step above</p>

#### Ben Jervis on 12/8/2019, 08:13 PM: 

<p>@Sam Harwell [MSFT] Quick update - Despite not having seen an update directly addressing this, I have not received the symptomatic dialogue box for a number of weeks now, so either my system has sorted itself out or it has been patched without me noticing.</p>

#### Feedback Bot on 3/31/2020, 05:23 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Elias Sadat on 4/1/2020, 06:42 AM: 

<p>I have the same issue. Had to downgrade to Visual Studio 2017 in order to continue development.</p>

#### Feedback Bot on 4/23/2020, 09:24 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Ben Jervis on 5/22/2020, 01:08 AM: 

Still happening every couple of weeks. &quot;Low priority&quot; background processes taking over everything and disallowing simple tasks such as typing or adding new files. 

---
#### tung solved on 11/9/2019, 11:58 AM, 0 votes: 

<p>Also facing this issue with VS2019. VS does not allows me to type normally when this process in running. It is so annoying.</p>

**Comment by sharwell** [comment]
This issue occurred due to a cyclic project reference (a project **Impulse4.vbproj** referenced itself with a `ProjectReference`).

The resulting deadlock occurred with the following async stack:

```
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.SemaphoreSlimExtensions.DisposableWaitAsync(System.Threading.SemaphoreSlim semaphore, System.Threading.CancellationToken cancellationToken) Line 21	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.SolutionState solution, bool lockGate, System.Threading.CancellationToken cancellationToken) Line 412	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(Microsoft.CodeAnalysis.SolutionState solution, System.Threading.CancellationToken cancellationToken) Line 322	C#
>	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetMetadataReferenceAsync(Microsoft.CodeAnalysis.SolutionState solution, Microsoft.CodeAnalysis.ProjectState fromProject, Microsoft.CodeAnalysis.ProjectReference projectReference, System.Threading.CancellationToken cancellationToken) Line 715	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(Microsoft.CodeAnalysis.SolutionState solution, Microsoft.CodeAnalysis.Compilation compilation, System.Threading.CancellationToken cancellationToken) Line 640	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoFromScratchAsync(Microsoft.CodeAnalysis.SolutionState solution, Microsoft.CodeAnalysis.SolutionState.CompilationTracker.State state, System.Threading.CancellationToken cancellationToken) Line 485	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(Microsoft.CodeAnalysis.SolutionState solution, bool lockGate, System.Threading.CancellationToken cancellationToken) Line 417	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(Microsoft.CodeAnalysis.SolutionState solution, System.Threading.CancellationToken cancellationToken) Line 322	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(System.Threading.CancellationToken cancellationToken) Line 258	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetSemanticModelForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan span, System.Threading.CancellationToken cancellationToken) Line 67	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken) Line 39	C#
```

Marking **help wanted** to ensure `GetMetadataReferenceAsync` does not attempt to call `GetCompilationAsync` on a compilation that itself is waiting for the call to `GetMetadataReferenceAsync` to complete.

**Comment by CyrusNajmabadi** [comment]
> This issue occurred due to a cyclic project reference (a project Impulse4.vbproj referenced itself with a ProjectReference).

Can we detect and reject this more up front?  Note: by 'reject' that either means one of:

1. not allowing this to load.
2. allowing it to load, but breaking the reference so taht we only operate on an acyclic graph.

**Comment by sharwell** [comment]
🔗 This was also the root cause of AB#1091086

**Comment by sharwell** [comment]
🔗 This was also the root cause of AB#1049578

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of hits in many years.
