### PR TITLE
Caching compiler: support binary additional texts

### LINKED ISSUE #84889: Compiler output cache fails on binary AdditionalFiles with CS2015
### Describe the bug

Enabling the experimental compiler output cache causes an otherwise successful compiler-server build to fail when a binary file is passed through `AdditionalFiles`:

```text
CSC : error CS2015: '.../TestLibrary.dll' is a binary file instead of a text file
```

The same DLL is correctly resolved by MSBuild as a project reference and appears in the compiler response as both:

```text
/reference:.../TestLibrary.dll
/additionalfile:.../TestLibrary.dll
```

The build succeeds without `use-global-cache` and fails on the first cache miss with it enabled.

Binary `AdditionalFiles` are used by generators that inspect `AdditionalText.Path` and read the file themselves. This previously regressed in #59209 and was fixed so the compiler would not eagerly read the content.

### Root cause

The cache path calls `Compilation.GetDeterministicKey(...)` before compilation. `DeterministicKeyBuilder.writeAdditionalTexts()` unconditionally calls `additionalText.GetText(cancellationToken)` for every additional file:

https://github.com/dotnet/roslyn/blob/9624511b64ead198424267624ff96ce9a7869307/src/Compilers/Core/Portable/Compilation/DeterministicKeyBuilder.cs#L164-L177

This eagerly reads a binary additional file as source text and adds CS2015 to the compilation. The runtime test wrapper generator intentionally passes resolved project-reference assemblies as `AdditionalFiles` here:

https://github.com/dotnet/runtime/blob/2580b590a05d8094853482acf0faa9ecbf06f2fc/src/tests/Common/XUnitWrapperGenerator/XUnitWrapperGenerator.props#L20-L28

### Reproduction

1. Create an MSBuild project using a source generator that receives a DLL through `AdditionalFiles` but does not call `GetText()` on it.
2. Build normally with shared compilation enabled; the build succeeds.
3. Rebuild with `/p:Features=use-global-cache=/tmp/roslyn-cache`; the compiler server fails with CS2015 on the DLL.

This was reproduced with compiler version `5.10.0-1.26379.102 (813f634ceb016018f5acc9bd3c2b16e17dff4686)`.

An isolated compiler-server log shows:

```text
Compilation cache enabled at: /tmp/roslyn-cache
Begin ... C# compiler run
Cache miss: taskbased-asyncfibonacci-with-yields.dll [...]
Return code: 1
Output:
error CS2015: '.../TestLibrary.dll' is a binary file instead of a text file
```

Invoking `csc.dll` directly with the exact captured response file and the same `/features:use-global-cache=...` argument succeeds, confirming the failure is in the compiler-server cache path rather than MSBuild reference resolution or command-line parsing.

### Expected behavior

Cache key generation should preserve existing `AdditionalFiles` behavior. If an additional file cannot be represented as text, the cache should either key it by its binary contents or skip caching that compilation without changing the compilation result.

> [!NOTE]
> This issue was drafted and filed with GitHub Copilot.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes https://github.com/dotnet/roslyn/issues/84889.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/84916)

### CODE REVIEW

File: src/Compilers/Core/Portable/Compilation/DeterministicKeyBuilder.cs [hunk 1]
```diff
@@ -173,7 +173,18 @@ void writeAdditionalTexts()
                     writer.WriteObjectStart();
                     WriteFilePath(writer, "fileName", additionalText.Path, pathMap, options);
                     writer.WriteKey("text");
-                    WriteSourceText(writer, additionalText.GetText(cancellationToken));
+
+                    // Generators can consume binary additional files by reading Path directly, so hash command-line files without decoding them.
+                    if (additionalText is AdditionalTextFile additionalTextFile)
+                    {
+                        using var stream = additionalTextFile.OpenRead();
+                        WriteStream(writer, stream);
```
[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Compilers/Core/Portable/Compilation/DeterministicKeyBuilder.cs:181]: I think mutating inputs during build is a generally unsupported scenario.

**Review by 333fred — APPROVED** [review]
