### ISSUE TITLE
when a function includes both a ref and out parameter CS8352 is now thrown

### ISSUE THREAD

**Issue by bbarry** [dotnet/roslyn#65417]
**Version Used**:  17.4 (worked in 17.3)

**Steps to Reproduce**:

```csharp
public class Foo
{
    public static void Outer()
    {
        var input = ReadOnlySpan<char>.Empty;
        var state = 0;

        while (Inner(input, ref state, out var rest))
        {
            input = rest;
        }
    }

    private static bool Inner(ReadOnlySpan<char> input, ref int state, out ReadOnlySpan<char> rest)
    {
        rest = ReadOnlySpan<char>.Empty;
        return false;
    }
}
```

vs:

```csharp
public class Foo
{
    public static void Outer()
    {
        var input = ReadOnlySpan<char>.Empty;

        while (Inner(input, out var rest))
        {
            input = rest;
        }
    }

    private static bool Inner(ReadOnlySpan<char> input, out ReadOnlySpan<char> rest)
    {
        rest = ReadOnlySpan<char>.Empty;
        return false;
    }
}
```

**Diagnostic Id**: CS8352

**Expected Behavior**:

Ideally working code in 17.3 remains working code in 17.4.

Assuming this is an intended spec change at least should be well documented as a breaking change somewhere.

If it is a spec change, why would the `ref` parameter make a difference (why does the second compile still in 17.4)?

**Actual Behavior**:

In 17.3 both code samples compile. In 17.4 the first one throws an error CS8352 on the line `input = rest;`

**Comment by bbarry** [comment]
I am able to work around it by changing the parameter `rest` to a `ref` parameter:

```csharp
public class Foo
{
    public static void Outer()
    {
        var input = ReadOnlySpan<char>.Empty;
        var state = 0;
        ReadOnlySpan<char> rest = default;

        while (Inner(input, ref state, ref rest))
        {
            input = rest;
        }
    }

    private static bool Inner(ReadOnlySpan<char> input, ref int state, ref ReadOnlySpan<char> rest)
    {
        rest = ReadOnlySpan<char>.Empty;
        return false;
    }
}
```

**Comment by cston** [comment]
@bbarry, thanks for reporting this.

The breaking change is expected. With the addition of ref field support in C#11, the compiler assumes that `ref` or `in` parameters to a method may be captured in a `ref struct` returned from the method - either returned directly or returned in an `out` parameter.

The breaking change is described [here](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#method-ref-struct-return-escape-analysis-depends-on-ref-escape-of-ref-arguments), although that description only mentions `ref struct` return values and should also include `ref struct` instances returned through `out` parameters.

As you described, one work around is to change the `out` parameter to `ref`. That resolves the error because the _ref-safe-to-escape_ of `ref int state` is _return-only_ - that is, the `ref` can be _returned_ (either as a `ref int`, or in a `ref struct` return value, or in an `out` parameter of `ref struct` type) but not captured in a `ref` parameter of `ref struct` type.

Alternatively, the `state` parameter could be annotated as `scoped ref` if the `ref` is not captured or returned.

**Comment by bbarry** [comment]
> Alternatively, the `state` parameter could be annotated as `scoped ref` if the `ref` is not captured or returned.

... but only if you are using C#11 (and targeting net7.0 / is it possible to use 11 while targeting netstandard2.0 or net6.0?). 

The above code is all C#10 (targeting net6.0).

I feel like it would be helpful to identify and acknowledge breaking changes to previous versions of the language when updating the compiler.

**Comment by cston** [comment]
Updated breaking change [description](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#method-ref-struct-return-escape-analysis-depends-on-ref-escape-of-ref-arguments) to include `ref` parameters returned through `out` parameters.
