### ISSUE TITLE
Unable to enforce some IDE rules on build because of EnforceOnBuild.Never

### ISSUE THREAD

**Issue by FrediKats** [dotnet/roslyn#77120]
**Brief description:**

Developers cannot enable enforce on build for some IDE rules. In my case it's IDE0001 and IDE0049.
I found related TODO in code: https://github.com/dotnet/roslyn/blob/main/src/Analyzers/Core/Analyzers/EnforceOnBuildValues.cs#L134.

It's very strange for me to disallow setting "warning" or "error" severity for some rules because of performance. Developers can disable rules in case of performance issues. For example, recently we found out that IDE0005 takes about 11-14 minutes (out of 18 minutes for all analyzers) of build time in our solution. And we successfully disabled only this rule.

Maybe it's better to change all `EnforceOnBuild.Never` to `EnforceOnBuild.WhenExplicitlyEnabled`?

cc: @mavasani

**Comment by xtqqczze** [comment]
`CSharpSimplifyTypeNamesDiagnosticAnalyzer` performance issues tracked by https://github.com/dotnet/roslyn/issues/18950

**Comment by glen-84** [comment]
The performance precondition in the TODO no longer has an open tracking item. #18950, the `CSharpSimplifyTypeNamesDiagnosticAnalyzer` performance issue linked above, was closed as not planned on 2025-10-14 with "This analyzer was heavily rewritten."

Current behavior on SDK 10.0.300:

```ini
# .editorconfig
[*.cs]
dotnet_diagnostic.IDE0001.severity = error
dotnet_diagnostic.IDE0002.severity = error
dotnet_diagnostic.IDE0004.severity = error
```

```csharp
using System;
using System.Collections.Generic;

class Probe
{
    System.Collections.Generic.List<string> _names = [];

    void Run()
    {
        System.Console.WriteLine((int)42);
        Console.WriteLine(_names.Count);
    }
}
```

`dotnet build -p:EnforceCodeStyleInBuild=true` fails, but only on IDE0004:

```text
Program.cs(10,34): error IDE0004: Cast is redundant.
```

The IDE0001 on line 6 and the IDE0002 on line 10 are not reported, and nothing in the build output indicates that those two severities were ignored. `dotnet format style --verify-no-changes --diagnostics IDE0001 IDE0002 --severity error` reports both on the same file and exits 2, so the analyzers themselves are fine; only the build path is gated.

IDE0004 in that same output is the precedent for what this issue asks for. It sits at `EnforceOnBuild.WhenExplicitlyEnabled` carrying its own performance TODO, pointing at #43304, which is also closed now. That bucket is strictly opt-in: dropping the `dotnet_diagnostic.IDE0004.severity` line from the `.editorconfig` above makes the same build clean again, so a rule in it costs nothing until someone names it.

Moving `SimplifyNames`, `SimplifyMemberAccess`, `RemoveQualification`, `AddQualification`, and `PreferBuiltInOrFrameworkType` to `WhenExplicitlyEnabled` would give those rules the same deal and leave the default build cost unchanged, which seems like the narrowest version of the change proposed above.

It would also cover #53215 and #71741, which ask for this per rule. The objection recorded in #53215 was that IDE0003 shares the analysis code behind IDE0001 and so could not be enabled on build on its own. Under `WhenExplicitlyEnabled` that no longer has to be resolved first: the shared analyzer runs only for projects that have set a severity for one of the rules it backs.

_Drafted by Claude (Anthropic AI assistant)._

**Comment by glen-84** [comment]
@xtqqczze Is there something inaccurate in my comment, or that you disagree with?
