### ISSUE TITLE
16.8 -> 16.9 Regression: code now gives compile error

### ISSUE THREAD

**Issue by ssa3512** [dotnet/roslyn#51689]
**Version Used**: 
16.9

**Steps to Reproduce**:

1.  Create a new csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```
2.  Add a single file `Test.cs`
```cs
public class Class1
{
    public void Test(bool condition, DateTime date)
    {
        short effectiveYear = (condition) 
            ? (short)date.Year
            : 1900;
    }
}
```
3. Compile with VS 2019 16.8
4. Upgrade to VS 2019 16.9

**Expected Behavior**:
Code continues to compile
**Actual Behavior**:
Code fails to compile with `error CS0266: Cannot implicitly convert type 'int' to 'short'. An explicit conversion exists (are you missing a cast?)`

Sharplab: [latest](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgEwCMAsAFBEDMABKfQML0De19XjDTzG0KJSrd2nUdzqMALPQAqcWAApgAe1UZ6AY1UA7bGhho9SegBEI8OWjBx62S3ACU4iWJFuJUABaqEMejgAMyC4LSMANzgATTgIBHoAXnolHX1DY10neldPNwB+FJ8/GCcHeAA6WPjcvNEQejIATgAGFoBuWu4AX1zeqm6gA==)
Sharplab: [NET Framework x64](https://sharplab.io/#v2:EYLgHgbALANALiAlgGxgExAagD4AEBMAjALABQuAzAAQFUDCVA3mVazdbXcgIYDOvJUmyYthbSjShUAKgFNecABTAA9iuRUAxioB2aRHES6YVACLc4s6YgC2sqmguyAlKLEih7sbwAWKgE5wVLIAZiGymoYAbrIAmrLc/lQAvFSK2noGRjrOVG5e7gD8ab4BcM6OlgB08Yn5BcIgVIQAnAAMbQDc9WwAvvn9pL1AA===)

**Comment by Youssef1313** [comment]
@ssa3512 This unfortunately was accidentally allowed in .NET 5.0.103 and VS 16.8, and the current behavior is the expected. See https://github.com/dotnet/roslyn/issues/49598.

Duplicate of #51674, #51624, and #51597
