### ISSUE TITLE
Razor build regression in .NET 6.0 when class and namespace have the same name

### ISSUE THREAD

**Issue by NCarlsonMSFT** [dotnet/roslyn#85395]
I've run into an issue in the Service Fabric tools where the templates do not work on .NET 6.0 due to the namespace and service name having the same name (this workes in .NET 5.0).

The specific error in .NET 6.0 is:
\TestProject\Pages\_ViewImports.cshtml(1,7): error CS0138: A 'using namespace' directive can only be applied to namespaces; 'TestProject' is a type not a namespace. Consider a 'using static' directive instead [\TestProject\TestProject.csproj]

A script for making a minimized repro:
```powershell
dotnet new webapp -o 'TestProject' -f 'net5.0'

# Update the project to target 5.0 and 6.0
$projFile = Get-Content -Path "TestProject\TestProject.csproj"
$projFile = $projFile -replace "<TargetFramework>net5.0</TargetFramework>", "<TargetFrameworks>net5.0;net6.0</TargetFrameworks>"
Set-Content -Path "TestProject\TestProject.csproj" -Value $projFile

# Add the conflicting class name
Set-Content -Path "TestProject\TestProject.cs" -Value "namespace TestProject { internal class TestProject { } }"

# Build in 5.0
dotnet build 'TestProject\TestProject.csproj' -f 'net5.0' -v q | Out-File 'net5.log'
if ($?) {
    Write-Host "Building 5.0 worked" -ForegroundColor 'Green'
}
else {
    Write-Host "Building 5.0 failed" -ForegroundColor 'Red'
}

# Build in 6.0
dotnet build 'TestProject\TestProject.csproj' -f 'net6.0' -v q | Out-File 'net6.log'
if ($?) {
    Write-Host "Building 6.0 worked" -ForegroundColor 'Green'
}
else {
    Write-Host "Building 6.0 failed" -ForegroundColor 'Red'
}
```

Additional context: I discovered when attempting to make the minimized repro that if the class TestProject is public this fails in 5.0 too.
