### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

File: docs/ide/README.md [hunk 1]
```diff
@@ -19,21 +20,25 @@
 
 ## <a id="prod-16"></a> dev16
 
-### <a id="prod-16-6"></a> 16.6 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes))
+### <a id="prod-16-7"></a> 16.7 ([release notes](https://docs.microsoft.com/visualstudio/releases/2019/release-notes))
+
+TO BE ADDED
```
Comment (Youssef1313) [inline docs/ide/README.md:25]:
```
    SQL Server Project is crashing when editing columns using design panel.
    SQL Server Database project : Fast scrolling in Design View of a table crashes VS
    CImage::Draw() has ambiguous call to DrawImage() in 16.7.0 Preview1
    Compiler Error when lowering x86 switch statements
    arm64: function too large after upgrade from 15.9.16 to 16.4.11
    Arm64: Indirect register (x8) contains invalid value at start of function
    Unexpected error C2027: use of undefined type when using templates with /permissive-
    Fixed a bug causing the C++ compiler to crash when building NanoRange
```

Are these what should be added here?
